import type { Question } from './schema';

export const questions: Question[] = [
  {
    id: "ip-strategy-1",
    type: "identify-pattern",
    category: "behavioral",
    grade: "middle",
    prompt: {
      ru: "Какой паттерн проектирования использован в этом коде?",
      en: "Какой паттерн проектирования использован в этом коде?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "interface Compressor { compress(data: string): string; }",
          "class Zip implements Compressor { compress(d: string) { return `zip(${d})`; } }",
          "class Gzip implements Compressor { compress(d: string) { return `gzip(${d})`; } }",
          "",
          "class Archiver {",
          "  constructor(private algo: Compressor) {}",
          "  use(algo: Compressor) { this.algo = algo; } // алгоритм задаётся извне",
          "  run(data: string) { return this.algo.compress(data); }",
          "}",
        ].join('\n'),
        en: [
          "interface Compressor { compress(data: string): string; }",
          "class Zip implements Compressor { compress(d: string) { return `zip(${d})`; } }",
          "class Gzip implements Compressor { compress(d: string) { return `gzip(${d})`; } }",
          "",
          "class Archiver {",
          "  constructor(private algo: Compressor) {}",
          "  use(algo: Compressor) { this.algo = algo; } // алгоритм задаётся извне",
          "  run(data: string) { return this.algo.compress(data); }",
          "}",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "State",
        "Strategy",
        "Observer",
        "Factory Method",
      ],
      en: [
        "State",
        "Strategy",
        "Observer",
        "Factory Method",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "Алгоритм сжатия внедряется извне и заменяется методом use(), а Archiver лишь делегирует ему работу — это Strategy. Не State: переключение не вызвано внутренними переходами объекта, состояние Archiver не управляет выбором. Не Observer: нет подписчиков и рассылки уведомлений «один ко многим». Не Factory Method: объект не создаётся подклассом, а передаётся готовым извне.",
      en: "Алгоритм сжатия внедряется извне и заменяется методом use(), а Archiver лишь делегирует ему работу — это Strategy. Не State: переключение не вызвано внутренними переходами объекта, состояние Archiver не управляет выбором. Не Observer: нет подписчиков и рассылки уведомлений «один ко многим». Не Factory Method: объект не создаётся подклассом, а передаётся готовым извне.",
    },
    conceptId: "strategy",
  },
  {
    id: "ip-state-1",
    type: "identify-pattern",
    category: "behavioral",
    grade: "senior",
    prompt: {
      ru: "Какой паттерн проектирования использован в этом коде?",
      en: "Какой паттерн проектирования использован в этом коде?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "interface DocState { publish(doc: Article): void; }",
          "class Draft implements DocState {",
          "  publish(doc: Article) { doc.setState(new Moderation()); } // переход задаёт само состояние",
          "}",
          "class Moderation implements DocState {",
          "  publish(doc: Article) { doc.setState(new Published()); }",
          "}",
          "class Published implements DocState {",
          "  publish(_doc: Article) { /* уже опубликовано — переходов нет */ }",
          "}",
          "",
          "class Article {",
          "  private state: DocState = new Draft();",
          "  setState(s: DocState) { this.state = s; }",
          "  publish() { this.state.publish(this); } // поведение зависит от состояния",
          "}",
        ].join('\n'),
        en: [
          "interface DocState { publish(doc: Article): void; }",
          "class Draft implements DocState {",
          "  publish(doc: Article) { doc.setState(new Moderation()); } // переход задаёт само состояние",
          "}",
          "class Moderation implements DocState {",
          "  publish(doc: Article) { doc.setState(new Published()); }",
          "}",
          "class Published implements DocState {",
          "  publish(_doc: Article) { /* уже опубликовано — переходов нет */ }",
          "}",
          "",
          "class Article {",
          "  private state: DocState = new Draft();",
          "  setState(s: DocState) { this.state = s; }",
          "  publish() { this.state.publish(this); } // поведение зависит от состояния",
          "}",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "Strategy",
        "State",
        "Observer",
        "Abstract Factory",
      ],
      en: [
        "Strategy",
        "State",
        "Observer",
        "Abstract Factory",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "Переходы Draft → Moderation → Published инициируют сами объекты-состояния, назначая контексту следующее состояние, а метод publish() ведёт себя по-разному в зависимости от текущего состояния — это State. Не Strategy: алгоритм не выбирается клиентом извне, переключение происходит внутри по логике самих состояний. Не Observer: нет подписчиков и уведомлений. Не Abstract Factory: ничего не порождается семействами — меняется поведение, а не создаются объекты.",
      en: "Переходы Draft → Moderation → Published инициируют сами объекты-состояния, назначая контексту следующее состояние, а метод publish() ведёт себя по-разному в зависимости от текущего состояния — это State. Не Strategy: алгоритм не выбирается клиентом извне, переключение происходит внутри по логике самих состояний. Не Observer: нет подписчиков и уведомлений. Не Abstract Factory: ничего не порождается семействами — меняется поведение, а не создаются объекты.",
    },
    conceptId: "state",
  },
  {
    id: "ip-observer-1",
    type: "identify-pattern",
    category: "behavioral",
    grade: "middle",
    prompt: {
      ru: "Какой паттерн проектирования использован в этом коде?",
      en: "Какой паттерн проектирования использован в этом коде?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "interface Subscriber { notify(headline: string): void; }",
          "",
          "class NewsAgency {",
          "  private subscribers: Subscriber[] = [];",
          "  subscribe(s: Subscriber) { this.subscribers.push(s); }",
          "  publish(headline: string) {",
          "    for (const s of this.subscribers) s.notify(headline); // рассылка всем",
          "  }",
          "}",
          "",
          "class EmailReader implements Subscriber {",
          "  notify(headline: string) { console.log(`Письмо: ${headline}`); }",
          "}",
        ].join('\n'),
        en: [
          "interface Subscriber { notify(headline: string): void; }",
          "",
          "class NewsAgency {",
          "  private subscribers: Subscriber[] = [];",
          "  subscribe(s: Subscriber) { this.subscribers.push(s); }",
          "  publish(headline: string) {",
          "    for (const s of this.subscribers) s.notify(headline); // рассылка всем",
          "  }",
          "}",
          "",
          "class EmailReader implements Subscriber {",
          "  notify(headline: string) { console.log(`Письмо: ${headline}`); }",
          "}",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "Observer",
        "Strategy",
        "State",
        "Factory Method",
      ],
      en: [
        "Observer",
        "Strategy",
        "State",
        "Factory Method",
      ],
    },
    correctIndex: 0,
    explanation: {
      ru: "NewsAgency хранит список подписчиков и при публикации уведомляет каждого — это зависимость «один ко многим» с автоматическим оповещением, то есть Observer. Не Strategy: не выбирается взаимозаменяемый алгоритм, а рассылаются уведомления множеству получателей. Не State: поведение агентства не переключается при смене внутреннего состояния, переходов нет. Не Factory Method: подписчики не создаются агентством, а регистрируются готовыми через subscribe().",
      en: "NewsAgency хранит список подписчиков и при публикации уведомляет каждого — это зависимость «один ко многим» с автоматическим оповещением, то есть Observer. Не Strategy: не выбирается взаимозаменяемый алгоритм, а рассылаются уведомления множеству получателей. Не State: поведение агентства не переключается при смене внутреннего состояния, переходов нет. Не Factory Method: подписчики не создаются агентством, а регистрируются готовыми через subscribe().",
    },
    conceptId: "observer",
  },
  {
    id: "ip-factory-method-1",
    type: "identify-pattern",
    category: "creational",
    grade: "middle",
    prompt: {
      ru: "Какой паттерн проектирования использован в этом коде?",
      en: "Какой паттерн проектирования использован в этом коде?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "interface Transport { deliver(): string; }",
          "class Truck implements Transport { deliver() { return 'по дороге'; } }",
          "class Ship implements Transport { deliver() { return 'по морю'; } }",
          "",
          "abstract class Logistics {",
          "  protected abstract createTransport(): Transport; // тип решает подкласс",
          "  planDelivery(): string {",
          "    const transport = this.createTransport();",
          "    return transport.deliver();",
          "  }",
          "}",
          "class RoadLogistics extends Logistics { protected createTransport() { return new Truck(); } }",
          "class SeaLogistics extends Logistics { protected createTransport() { return new Ship(); } }",
        ].join('\n'),
        en: [
          "interface Transport { deliver(): string; }",
          "class Truck implements Transport { deliver() { return 'по дороге'; } }",
          "class Ship implements Transport { deliver() { return 'по морю'; } }",
          "",
          "abstract class Logistics {",
          "  protected abstract createTransport(): Transport; // тип решает подкласс",
          "  planDelivery(): string {",
          "    const transport = this.createTransport();",
          "    return transport.deliver();",
          "  }",
          "}",
          "class RoadLogistics extends Logistics { protected createTransport() { return new Truck(); } }",
          "class SeaLogistics extends Logistics { protected createTransport() { return new Ship(); } }",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "Abstract Factory",
        "Factory Method",
        "Strategy",
        "Observer",
      ],
      en: [
        "Abstract Factory",
        "Factory Method",
        "Strategy",
        "Observer",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "Базовый класс Logistics объявляет один фабричный метод createTransport(), а конкретный тип продукта выбирает подкласс через переопределение (наследование), создавая ровно один продукт — это Factory Method. Не Abstract Factory: здесь нет фабрики, порождающей семейство из нескольких связанных продуктов. Не Strategy: подкласс определяет, что создать, а не подставляет готовый алгоритм извне — речь о порождении объекта, а не о выборе поведения. Не Observer: нет подписчиков и уведомлений.",
      en: "Базовый класс Logistics объявляет один фабричный метод createTransport(), а конкретный тип продукта выбирает подкласс через переопределение (наследование), создавая ровно один продукт — это Factory Method. Не Abstract Factory: здесь нет фабрики, порождающей семейство из нескольких связанных продуктов. Не Strategy: подкласс определяет, что создать, а не подставляет готовый алгоритм извне — речь о порождении объекта, а не о выборе поведения. Не Observer: нет подписчиков и уведомлений.",
    },
    conceptId: "factory-method",
  },
  {
    id: "ip-abstract-factory-1",
    type: "identify-pattern",
    category: "creational",
    grade: "senior",
    prompt: {
      ru: "Какой паттерн проектирования использован в этом коде?",
      en: "Какой паттерн проектирования использован в этом коде?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "interface Chair { sit(): string; }",
          "interface Sofa { lie(): string; }",
          "",
          "interface FurnitureFactory {",
          "  createChair(): Chair; // семейство связанных продуктов",
          "  createSofa(): Sofa;",
          "}",
          "",
          "class ModernChair implements Chair { sit() { return 'модерн-стул'; } }",
          "class ModernSofa implements Sofa { lie() { return 'модерн-диван'; } }",
          "class VictorianChair implements Chair { sit() { return 'викторианский стул'; } }",
          "class VictorianSofa implements Sofa { lie() { return 'викторианский диван'; } }",
          "",
          "class ModernFactory implements FurnitureFactory {",
          "  createChair() { return new ModernChair(); }",
          "  createSofa() { return new ModernSofa(); }",
          "}",
          "class VictorianFactory implements FurnitureFactory {",
          "  createChair() { return new VictorianChair(); }",
          "  createSofa() { return new VictorianSofa(); }",
          "}",
        ].join('\n'),
        en: [
          "interface Chair { sit(): string; }",
          "interface Sofa { lie(): string; }",
          "",
          "interface FurnitureFactory {",
          "  createChair(): Chair; // семейство связанных продуктов",
          "  createSofa(): Sofa;",
          "}",
          "",
          "class ModernChair implements Chair { sit() { return 'модерн-стул'; } }",
          "class ModernSofa implements Sofa { lie() { return 'модерн-диван'; } }",
          "class VictorianChair implements Chair { sit() { return 'викторианский стул'; } }",
          "class VictorianSofa implements Sofa { lie() { return 'викторианский диван'; } }",
          "",
          "class ModernFactory implements FurnitureFactory {",
          "  createChair() { return new ModernChair(); }",
          "  createSofa() { return new ModernSofa(); }",
          "}",
          "class VictorianFactory implements FurnitureFactory {",
          "  createChair() { return new VictorianChair(); }",
          "  createSofa() { return new VictorianSofa(); }",
          "}",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "Factory Method",
        "Abstract Factory",
        "Strategy",
        "Observer",
      ],
      en: [
        "Factory Method",
        "Abstract Factory",
        "Strategy",
        "Observer",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "Интерфейс FurnitureFactory создаёт целое семейство связанных продуктов (Chair и Sofa), а каждая конкретная фабрика гарантирует их согласованность (всё «модерн» либо всё «викторианское») — это Abstract Factory. Не Factory Method: там один фабричный метод на один продукт с выбором через наследование, здесь же несколько методов создания и композиция фабрик. Не Strategy: фабрики порождают объекты, а не подменяют взаимозаменяемый алгоритм поведения. Не Observer: нет подписки и уведомлений.",
      en: "Интерфейс FurnitureFactory создаёт целое семейство связанных продуктов (Chair и Sofa), а каждая конкретная фабрика гарантирует их согласованность (всё «модерн» либо всё «викторианское») — это Abstract Factory. Не Factory Method: там один фабричный метод на один продукт с выбором через наследование, здесь же несколько методов создания и композиция фабрик. Не Strategy: фабрики порождают объекты, а не подменяют взаимозаменяемый алгоритм поведения. Не Observer: нет подписки и уведомлений.",
    },
    conceptId: "abstract-factory",
  },
  {
    id: "c-srp-1",
    type: "concept",
    category: "solid",
    grade: "junior",
    prompt: {
      ru: "Как точнее всего сформулировать Single Responsibility Principle?",
      en: "Как точнее всего сформулировать Single Responsibility Principle?",
    },
    options: {
      ru: [
        "У класса должна быть одна и только одна причина для изменения",
        "Класс должен быть открыт для расширения и закрыт для изменения",
        "Клиент не должен зависеть от методов, которые он не использует",
        "Подтип должен подставляться вместо своего базового типа",
      ],
      en: [
        "У класса должна быть одна и только одна причина для изменения",
        "Класс должен быть открыт для расширения и закрыт для изменения",
        "Клиент не должен зависеть от методов, которые он не использует",
        "Подтип должен подставляться вместо своего базового типа",
      ],
    },
    correctIndex: 0,
    explanation: {
      ru: "SRP: у модуля одна причина для изменения — он отвечает перед одним актором. Второй вариант описывает OCP, третий — ISP, четвёртый — LSP.",
      en: "SRP: у модуля одна причина для изменения — он отвечает перед одним актором. Второй вариант описывает OCP, третий — ISP, четвёртый — LSP.",
    },
    conceptId: "srp",
  },
  {
    id: "c-ocp-1",
    type: "concept",
    category: "solid",
    grade: "junior",
    prompt: {
      ru: "Что утверждает Open/Closed Principle?",
      en: "Что утверждает Open/Closed Principle?",
    },
    options: {
      ru: [
        "Высокоуровневые модули не должны зависеть от низкоуровневых",
        "Сущности должны быть открыты для расширения, но закрыты для изменения",
        "У модуля должна быть одна причина для изменения",
        "Много узких интерфейсов лучше одного «толстого»",
      ],
      en: [
        "Высокоуровневые модули не должны зависеть от низкоуровневых",
        "Сущности должны быть открыты для расширения, но закрыты для изменения",
        "У модуля должна быть одна причина для изменения",
        "Много узких интерфейсов лучше одного «толстого»",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "OCP: новое поведение добавляется расширением, а существующий код не меняется. Первый вариант — это DIP, третий — SRP, четвёртый — ISP.",
      en: "OCP: новое поведение добавляется расширением, а существующий код не меняется. Первый вариант — это DIP, третий — SRP, четвёртый — ISP.",
    },
    conceptId: "ocp",
  },
  {
    id: "c-lsp-1",
    type: "concept",
    category: "solid",
    grade: "junior",
    prompt: {
      ru: "Какое требование выражает Liskov Substitution Principle?",
      en: "Какое требование выражает Liskov Substitution Principle?",
    },
    options: {
      ru: [
        "Каждый класс отвечает ровно за одну ответственность",
        "Зависимости должны быть направлены на абстракции",
        "Объекты базового типа можно заменить объектами подтипа без нарушения корректности программы",
        "Поведение можно менять, не трогая существующий код",
      ],
      en: [
        "Каждый класс отвечает ровно за одну ответственность",
        "Зависимости должны быть направлены на абстракции",
        "Объекты базового типа можно заменить объектами подтипа без нарушения корректности программы",
        "Поведение можно менять, не трогая существующий код",
      ],
    },
    correctIndex: 2,
    explanation: {
      ru: "LSP: подтип обязан соблюдать контракт базового типа и быть подставляемым вместо него. Первый вариант — SRP, второй — DIP, четвёртый — OCP.",
      en: "LSP: подтип обязан соблюдать контракт базового типа и быть подставляемым вместо него. Первый вариант — SRP, второй — DIP, четвёртый — OCP.",
    },
    conceptId: "lsp",
  },
  {
    id: "c-isp-1",
    type: "concept",
    category: "solid",
    grade: "junior",
    prompt: {
      ru: "Что рекомендует Interface Segregation Principle?",
      en: "Что рекомендует Interface Segregation Principle?",
    },
    options: {
      ru: [
        "Дробить крупные интерфейсы на узкие, специфичные для клиента",
        "Подтип должен соблюдать контракт базового типа",
        "Класс не должен сам создавать свои зависимости",
        "У модуля должна быть одна причина для изменения",
      ],
      en: [
        "Дробить крупные интерфейсы на узкие, специфичные для клиента",
        "Подтип должен соблюдать контракт базового типа",
        "Класс не должен сам создавать свои зависимости",
        "У модуля должна быть одна причина для изменения",
      ],
    },
    correctIndex: 0,
    explanation: {
      ru: "ISP: клиент не должен зависеть от методов, которые не использует, поэтому «толстые» интерфейсы дробят на узкие роли. Второй вариант — LSP, третий отражает идею DIP, четвёртый — SRP.",
      en: "ISP: клиент не должен зависеть от методов, которые не использует, поэтому «толстые» интерфейсы дробят на узкие роли. Второй вариант — LSP, третий отражает идею DIP, четвёртый — SRP.",
    },
    conceptId: "isp",
  },
  {
    id: "c-dip-1",
    type: "concept",
    category: "solid",
    grade: "middle",
    prompt: {
      ru: "Что утверждает Dependency Inversion Principle?",
      en: "Что утверждает Dependency Inversion Principle?",
    },
    options: {
      ru: [
        "Интерфейсы должны быть как можно меньше",
        "У класса должна быть одна причина для изменения",
        "Наследники взаимозаменяемы с базовым классом",
        "Модули верхнего и нижнего уровня зависят от абстракций, а не друг от друга напрямую",
      ],
      en: [
        "Интерфейсы должны быть как можно меньше",
        "У класса должна быть одна причина для изменения",
        "Наследники взаимозаменяемы с базовым классом",
        "Модули верхнего и нижнего уровня зависят от абстракций, а не друг от друга напрямую",
      ],
    },
    correctIndex: 3,
    explanation: {
      ru: "DIP: и высокоуровневые, и низкоуровневые модули зависят от абстракций; детали зависят от абстракций, а не наоборот. Первый вариант — ISP, второй — SRP, третий — LSP.",
      en: "DIP: и высокоуровневые, и низкоуровневые модули зависят от абстракций; детали зависят от абстракций, а не наоборот. Первый вариант — ISP, второй — SRP, третий — LSP.",
    },
    conceptId: "dip",
  },
  {
    id: "t-srp-1",
    type: "tradeoff",
    category: "solid",
    grade: "junior",
    prompt: {
      ru: "В чём основной компромисс строгого следования SRP?",
      en: "В чём основной компромисс строгого следования SRP?",
    },
    options: {
      ru: [
        "Больше мелких классов и переходов между файлами в обмен на низкую связанность и лёгкость изменений",
        "SRP ускоряет выполнение программы ценой расхода памяти",
        "SRP избавляет от необходимости писать тесты",
        "SRP всегда уменьшает общее количество классов",
      ],
      en: [
        "Больше мелких классов и переходов между файлами в обмен на низкую связанность и лёгкость изменений",
        "SRP ускоряет выполнение программы ценой расхода памяти",
        "SRP избавляет от необходимости писать тесты",
        "SRP всегда уменьшает общее количество классов",
      ],
    },
    correctIndex: 0,
    explanation: {
      ru: "Разделение ответственностей снижает связанность и локализует изменения, но увеличивает число классов и стоимость навигации по коду. Остальные варианты неверны: SRP не про производительность, не отменяет тесты и обычно увеличивает число классов.",
      en: "Разделение ответственностей снижает связанность и локализует изменения, но увеличивает число классов и стоимость навигации по коду. Остальные варианты неверны: SRP не про производительность, не отменяет тесты и обычно увеличивает число классов.",
    },
    conceptId: "srp",
  },
  {
    id: "t-ocp-1",
    type: "tradeoff",
    category: "solid",
    grade: "junior",
    prompt: {
      ru: "Когда применение OCP скорее вредит, чем помогает?",
      en: "Когда применение OCP скорее вредит, чем помогает?",
    },
    options: {
      ru: [
        "Когда набор вариантов стабилен: абстракция ради расширения добавляет сложность без реальной выгоды",
        "Когда в проекте есть автотесты",
        "OCP полезен всегда и во всех случаях без исключений",
        "Когда проект написан на TypeScript",
      ],
      en: [
        "Когда набор вариантов стабилен: абстракция ради расширения добавляет сложность без реальной выгоды",
        "Когда в проекте есть автотесты",
        "OCP полезен всегда и во всех случаях без исключений",
        "Когда проект написан на TypeScript",
      ],
    },
    correctIndex: 0,
    explanation: {
      ru: "Гибкость OCP не бесплатна: если расширения не происходит, преждевременные абстракции лишь усложняют код (риск преждевременного обобщения). Наличие тестов и язык проекта к этому компромиссу отношения не имеют, а «полезен всегда» — как раз ложное утверждение.",
      en: "Гибкость OCP не бесплатна: если расширения не происходит, преждевременные абстракции лишь усложняют код (риск преждевременного обобщения). Наличие тестов и язык проекта к этому компромиссу отношения не имеют, а «полезен всегда» — как раз ложное утверждение.",
    },
    conceptId: "ocp",
  },
  {
    id: "t-dip-1",
    type: "tradeoff",
    category: "solid",
    grade: "middle",
    prompt: {
      ru: "Какой компромисс несёт применение Dependency Inversion Principle?",
      en: "Какой компромисс несёт применение Dependency Inversion Principle?",
    },
    options: {
      ru: [
        "DIP убирает все интерфейсы из проекта",
        "Развязка модулей и тестируемость достигаются ценой лишних абстракций и косвенности",
        "DIP ускоряет код за счёт отказа от полиморфизма",
        "DIP запрещает использовать конкретные классы где-либо в системе",
      ],
      en: [
        "DIP убирает все интерфейсы из проекта",
        "Развязка модулей и тестируемость достигаются ценой лишних абстракций и косвенности",
        "DIP ускоряет код за счёт отказа от полиморфизма",
        "DIP запрещает использовать конкретные классы где-либо в системе",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "DIP развязывает бизнес-логику и инфраструктуру и упрощает тестирование через подмену реализаций, но добавляет абстракции, косвенность и потребность во внедрении зависимостей. Остальные варианты искажают суть: DIP вводит абстракции, а не убирает их, не про скорость и не запрещает конкретные классы — он лишь инвертирует направление зависимости.",
      en: "DIP развязывает бизнес-логику и инфраструктуру и упрощает тестирование через подмену реализаций, но добавляет абстракции, косвенность и потребность во внедрении зависимостей. Остальные варианты искажают суть: DIP вводит абстракции, а не убирает их, не про скорость и не запрещает конкретные классы — он лишь инвертирует направление зависимости.",
    },
    conceptId: "dip",
  },
];
