import type { Concept } from '../schema';

export const solid: Concept[] = [
  {
    id: 'srp',
    name: 'Single Responsibility Principle',
    aka: ['SRP'],
    category: 'solid',
    grade: 'junior',
    tagline: 'У модуля должна быть одна причина для изменения',
    definition:
      'Модуль должен отвечать перед одним и только одним актором. Иначе говоря, у класса должна быть одна и только одна причина для изменения — он инкапсулирует одну ответственность.',
    problem:
      'Класс, который считает зарплату, форматирует отчёт и сохраняет данные в БД, меняется по трём независимым причинам: бухгалтерия, отдел отчётности и DBA. Правка ради одного актора рискует сломать логику другого, а тестировать такой класс тяжело.',
    solution:
      'Разделяем ответственности на отдельные классы: расчёт, хранение и форматирование. Каждый класс меняется независимо и отвечает перед своим актором.',
    codeExample: {
      lang: 'typescript',
      code: [
        '// Нарушение: три причины для изменения в одном классе',
        'class Employee {',
        '  calculatePay() { /* правила бухгалтерии */ }',
        '  save() { /* схема БД */ }',
        '  describeInReport() { /* формат отчёта */ }',
        '}',
        '',
        '// SRP: каждая ответственность в своём классе',
        'class PayCalculator { calculate(e: Employee): number { /* ... */ return 0; } }',
        'class EmployeeRepository { save(e: Employee): void { /* ... */ } }',
        'class EmployeeReport { render(e: Employee): string { /* ... */ return \'\'; } }',
      ].join('\n'),
    },
    pros: ['Проще тестировать и понимать', 'Ниже связанность', 'Изменения локальны и безопасны'],
    cons: ['Больше классов и файлов', 'Риск преждевременного дробления'],
    tradeoffs: ['Гранулярность против простоты навигации по коду'],
    whenToUse: ['Класс меняется по нескольким несвязанным причинам', 'В одном классе смешаны разные уровни абстракции'],
    whenNotToUse: ['Крошечная сущность, дробление которой добавит лишь шум'],
    related: ['ocp', 'dip'],
    tags: ['принципы', 'связанность'],
  },
  {
    id: 'ocp',
    name: 'Open/Closed Principle',
    aka: ['OCP'],
    category: 'solid',
    grade: 'junior',
    tagline: 'Открыт для расширения, закрыт для изменения',
    definition:
      'Программные сущности (классы, модули, функции) должны быть открыты для расширения, но закрыты для изменения: новое поведение добавляется без правки существующего кода.',
    problem:
      'Расчёт площади через switch по типу фигуры приходится править при каждой новой фигуре. Один и тот же проверенный код меняется снова и снова, повышая риск регрессий.',
    solution:
      'Вводим абстракцию Shape с методом area(). Новая фигура — это новый класс, реализующий интерфейс; код-потребитель не меняется вовсе.',
    codeExample: {
      lang: 'typescript',
      code: [
        '// Нарушение: добавление фигуры требует правки switch',
        'class AreaCalculator {',
        '  area(shape: { type: string; [k: string]: unknown }): number {',
        "    switch (shape.type) {",
        "      case 'circle': return Math.PI * (shape.r as number) ** 2;",
        "      case 'square': return (shape.side as number) ** 2;",
        '      default: return 0;',
        '    }',
        '  }',
        '}',
        '',
        '// OCP: новая фигура — новый класс, потребитель закрыт для правок',
        'interface Shape { area(): number; }',
        'class Circle implements Shape { constructor(private r: number) {} area() { return Math.PI * this.r ** 2; } }',
        'class Square implements Shape { constructor(private side: number) {} area() { return this.side ** 2; } }',
        'class Triangle implements Shape { constructor(private b: number, private h: number) {} area() { return 0.5 * this.b * this.h; } }',
        '',
        'function totalArea(shapes: Shape[]): number {',
        '  return shapes.reduce((sum, s) => sum + s.area(), 0); // не меняется при добавлении фигур',
        '}',
      ].join('\n'),
    },
    pros: ['Новое поведение без правки проверенного кода', 'Меньше регрессий', 'Расширяемость через полиморфизм'],
    cons: ['Больше абстракций заранее', 'Избыточная гибкость там, где изменений не будет'],
    tradeoffs: ['Гибкость к будущим изменениям против простоты «здесь и сейчас»'],
    whenToUse: ['В точке кода регулярно добавляются новые варианты', 'Требуется подключать поведение плагинами'],
    whenNotToUse: ['Набор вариантов стабилен и вряд ли расширится'],
    related: ['lsp', 'dip'],
    tags: ['принципы', 'расширяемость'],
  },
  {
    id: 'lsp',
    name: 'Liskov Substitution Principle',
    aka: ['LSP'],
    category: 'solid',
    grade: 'junior',
    tagline: 'Подтип должен подставляться вместо своего базового типа',
    definition:
      'Если S — подтип T, то объекты T можно заменять объектами S без нарушения корректности программы. Подтип обязан соблюдать контракт базового типа: не усиливать предусловия и не ослаблять постусловия.',
    problem:
      'Square наследует Rectangle и переопределяет setWidth/setHeight так, что ширина и высота меняются вместе. Клиент, работающий с Rectangle и ожидающий независимые стороны, получает неверную площадь при подстановке Square.',
    solution:
      'Не строим ложную иерархию «квадрат — это прямоугольник». Моделируем обе фигуры через общий интерфейс Shape, где каждая честно реализует свой контракт.',
    codeExample: {
      lang: 'typescript',
      code: [
        '// Нарушение LSP: Square ломает контракт Rectangle',
        'class Rectangle {',
        '  constructor(protected w: number, protected h: number) {}',
        '  setWidth(w: number) { this.w = w; }',
        '  setHeight(h: number) { this.h = h; }',
        '  area() { return this.w * this.h; }',
        '}',
        'class Square extends Rectangle {',
        '  setWidth(w: number) { this.w = w; this.h = w; }  // ломает ожидания клиента',
        '  setHeight(h: number) { this.w = h; this.h = h; }',
        '}',
        '// setWidth(5); setHeight(4); area() ждём 20, а Square вернёт 16',
        '',
        '// LSP: общий интерфейс без ложной иерархии',
        'interface Shape { area(): number; }',
        'class Rect implements Shape { constructor(private w: number, private h: number) {} area() { return this.w * this.h; } }',
        'class Sq implements Shape { constructor(private side: number) {} area() { return this.side ** 2; } }',
      ].join('\n'),
    },
    pros: ['Полиморфизм безопасен', 'Клиент не знает о подтипах', 'Меньше проверок instanceof'],
    cons: ['Требует дисциплины в проектировании иерархий', 'Иногда вынуждает отказаться от «удобного» наследования'],
    tradeoffs: ['Строгость контрактов против соблазна переиспользовать код наследованием'],
    whenToUse: ['Проектируется иерархия наследования', 'Код полагается на полиморфную подстановку'],
    whenNotToUse: ['Наследование не используется — принцип неактуален'],
    related: ['ocp'],
    tags: ['принципы', 'наследование'],
  },
  {
    id: 'isp',
    name: 'Interface Segregation Principle',
    aka: ['ISP'],
    category: 'solid',
    grade: 'junior',
    tagline: 'Не заставляйте клиента зависеть от методов, которые он не использует',
    definition:
      'Клиентов не следует принуждать зависеть от интерфейсов, которые они не используют. Много специализированных интерфейсов, заточенных под клиента, лучше одного «толстого».',
    problem:
      '«Толстый» интерфейс Worker с методами work() и eat() вынуждает класс Robot реализовывать eat() заглушкой-исключением. Клиент зависит от метода, который ему не нужен, а любое изменение eat() задевает Robot.',
    solution:
      'Дробим интерфейс на узкие роли Workable и Eatable. Класс реализует только то, что действительно умеет.',
    codeExample: {
      lang: 'typescript',
      code: [
        '// Нарушение: «толстый» интерфейс навязывает лишнее',
        'interface Worker {',
        '  work(): void;',
        '  eat(): void;',
        '}',
        'class Robot implements Worker {',
        '  work() { /* ... */ }',
        "  eat() { throw new Error('робот не ест'); } // вынужденная заглушка",
        '}',
        '',
        '// ISP: узкие интерфейсы под нужды клиента',
        'interface Workable { work(): void; }',
        'interface Eatable { eat(): void; }',
        'class Human implements Workable, Eatable { work() {} eat() {} }',
        'class Machine implements Workable { work() {} }',
      ].join('\n'),
    },
    pros: ['Клиент зависит только от нужного', 'Меньше эффекта ряби при изменениях', 'Реализации проще'],
    cons: ['Больше интерфейсов', 'Возможна фрагментация на слишком мелкие роли'],
    tradeoffs: ['Точность зависимостей против числа абстракций'],
    whenToUse: ['Интерфейс разросся и реализации имеют пустые методы', 'Разные клиенты используют разные части API'],
    whenNotToUse: ['Интерфейс мал и все методы нужны всем клиентам'],
    related: ['srp', 'dip'],
    tags: ['принципы', 'интерфейсы'],
  },
  {
    id: 'dip',
    name: 'Dependency Inversion Principle',
    aka: ['DIP'],
    category: 'solid',
    grade: 'middle',
    tagline: 'Зависимости направлены на абстракции, а не на детали',
    definition:
      'Модули верхнего уровня не должны зависеть от модулей нижнего уровня — оба зависят от абстракций. Абстракции не зависят от деталей; детали зависят от абстракций.',
    problem:
      'Класс UserService напрямую создаёт MySqlDatabase. Высокоуровневая бизнес-логика жёстко привязана к конкретной СУБД: её нельзя подменить в тестах и трудно заменить на другое хранилище.',
    solution:
      'Вводим абстракцию Database, от которой зависит и UserService, и конкретная реализация. Реализацию внедряем извне (через конструктор), инвертируя направление зависимости.',
    codeExample: {
      lang: 'typescript',
      code: [
        '// Нарушение: высокоуровневый модуль зависит от конкретной детали',
        'class MySqlDatabase { save(data: string) { /* ... */ } }',
        'class UserServiceBad {',
        '  private db = new MySqlDatabase(); // жёсткая связь с реализацией',
        '  register(user: string) { this.db.save(user); }',
        '}',
        '',
        '// DIP: оба уровня зависят от абстракции, деталь внедряется извне',
        'interface Database { save(data: string): void; }',
        'class MySqlDatabase2 implements Database { save(data: string) { /* ... */ } }',
        'class InMemoryDatabase implements Database { save(data: string) { /* ... */ } }',
        'class UserService {',
        '  constructor(private db: Database) {} // зависимость от интерфейса',
        '  register(user: string) { this.db.save(user); }',
        '}',
      ].join('\n'),
    },
    pros: ['Реализации взаимозаменяемы', 'Легко подставить mock в тестах', 'Бизнес-логика не знает о деталях'],
    cons: ['Больше интерфейсов и косвенности', 'Нужен механизм внедрения зависимостей'],
    tradeoffs: ['Развязка модулей против прямолинейности и числа абстракций'],
    whenToUse: ['Бизнес-логика не должна знать о конкретной инфраструктуре', 'Нужна подмена реализации в тестах или конфигурации'],
    whenNotToUse: ['Деталь стабильна и никогда не заменится — абстракция будет лишней'],
    related: ['ocp', 'isp'],
    tags: ['принципы', 'внедрение зависимостей'],
  },
];
