import type { Concept, Question } from '../schema';

export const tradeoffs: Concept[] = [
  {
    id: "composition-vs-inheritance",
    name: "Composition vs Inheritance",
    category: "tradeoff",
    grade: "middle",
    tagline: {
      ru: "Собирать поведение из объектов или наследовать его от класса",
      en: "Assemble behavior from objects, or inherit it from a class",
    },
    definition: {
      ru: "Сравнение двух механизмов переиспользования кода: class inheritance — переиспользование «белым ящиком» (подкласс видит детали родителя и расширяет его переопределением) и object composition — переиспользование «чёрным ящиком» (объект собирается из других объектов и делегирует им работу через интерфейсы). Классическая рекомендация GoF: «Favor object composition over class inheritance» — предпочитайте композицию объектов наследованию классов.",
      en: "A comparison of two code-reuse mechanisms: class inheritance is \"white-box\" reuse (a subclass sees the parent's internals and extends it by overriding), while object composition is \"black-box\" reuse (an object is assembled from other objects and delegates work to them through interfaces). The classic GoF guideline: \"Favor object composition over class inheritance.\"",
    },
    problem: {
      ru: "Наследование фиксирует связь на этапе компиляции: поведение нельзя заменить в рантайме, а подкласс завязан на детали реализации родителя — изменение базового класса ломает наследников (fragile base class). Когда поведение варьируется по нескольким независимым осям (формат, доставка, сжатие), иерархия разрастается комбинаторно: подкласс на каждую комбинацию.",
      en: "Inheritance fixes the relationship at compile time: behavior can't be swapped at runtime, and a subclass is bound to the parent's implementation details, so changing the base class breaks its subclasses (the fragile base class problem). When behavior varies along several independent axes (format, delivery, compression), the hierarchy grows combinatorially: one subclass per combination.",
    },
    solution: {
      ru: "Вместо расширения базового класса объект составляется из частей, скрытых за интерфейсами, и делегирует им работу. Вариант поведения меняется заменой части — в том числе в рантайме, а зависимость идёт только на интерфейс, не на реализацию. Наследование остаётся для истинного отношения «is-a» со стабильным контрактом и соблюдением LSP.",
      en: "Instead of extending a base class, an object is assembled from parts hidden behind interfaces and delegates work to them. A behavior variant changes by swapping a part, at runtime too, and the dependency is on the interface only, not the implementation. Inheritance is reserved for a genuine \"is-a\" relationship with a stable contract that honors the LSP.",
    },
    codeExample: {
      lang: "typescript",
      code: {
        ru: [
          "// Наследование: вариант поведения зашит в иерархию классов",
          "class TextReport { render(data: string) { return `report(${data})`; } }",
          "class PdfTextReport extends TextReport { render(d: string) { return `pdf(${super.render(d)})`; } }",
          "// нужен ещё сжатый вариант? ZippedPdfTextReport, ZippedHtmlTextReport... — взрыв подклассов",
          "",
          "// Композиция: поведение собирается из частей за интерфейсом",
          "interface Formatter { format(data: string): string; }",
          "class PdfFormatter implements Formatter { format(d: string) { return `pdf(${d})`; } }",
          "class HtmlFormatter implements Formatter { format(d: string) { return `html(${d})`; } }",
          "",
          "class Report {",
          "  constructor(private formatter: Formatter) {} // has-a вместо is-a",
          "  render(data: string) { return this.formatter.format(data); }",
          "}",
          "",
          "const report = new Report(new PdfFormatter());",
          "report.render('Q3'); // формат меняется заменой части, без новой иерархии",
        ].join('\n'),
        en: [
          "// Inheritance: the behavior variant is baked into the class hierarchy",
          "class TextReport { render(data: string) { return `report(${data})`; } }",
          "class PdfTextReport extends TextReport { render(d: string) { return `pdf(${super.render(d)})`; } }",
          "// need a compressed variant too? ZippedPdfTextReport, ZippedHtmlTextReport... — a subclass explosion",
          "",
          "// Composition: behavior is assembled from parts behind an interface",
          "interface Formatter { format(data: string): string; }",
          "class PdfFormatter implements Formatter { format(d: string) { return `pdf(${d})`; } }",
          "class HtmlFormatter implements Formatter { format(d: string) { return `html(${d})`; } }",
          "",
          "class Report {",
          "  constructor(private formatter: Formatter) {} // has-a instead of is-a",
          "  render(data: string) { return this.formatter.format(data); }",
          "}",
          "",
          "const report = new Report(new PdfFormatter());",
          "report.render('Q3'); // the format changes by swapping a part, with no new hierarchy",
        ].join('\n'),
      },
    },
    pros: {
      ru: [
        "Композиция позволяет заменять поведение в рантайме — наследование фиксирует его при компиляции",
        "Независимые оси поведения комбинируются сборкой частей, без комбинаторного взрыва подклассов",
        "Инкапсуляция сохраняется: объект зависит от интерфейса части, а не от деталей базового класса",
        "Части легко подменяются в тестах фейками",
      ],
      en: [
        "Composition lets you swap behavior at runtime, whereas inheritance fixes it at compile time",
        "Independent axes of behavior combine by assembling parts, with no combinatorial explosion of subclasses",
        "Encapsulation is preserved: an object depends on a part's interface, not on the base class's internals",
        "Parts are easily swapped out for fakes in tests",
      ],
    },
    cons: {
      ru: [
        "Больше объектов и делегирующего кода-обвязки",
        "Поведение размазано по нескольким объектам — труднее проследить целиком",
        "Для простого и стабильного «is-a» наследование короче и прямее",
      ],
      en: [
        "More objects and delegating boilerplate",
        "Behavior is spread across several objects, making it harder to follow end to end",
        "For a simple, stable \"is-a\", inheritance is shorter and more direct",
      ],
    },
    tradeoffs: {
      ru: [
        "Гибкость сборки и замены поведения в рантайме против косвенности и числа объектов",
        "Переиспользование «чёрным ящиком» через интерфейсы против лаконичности «белого ящика» наследования",
        "Защита от fragile base class против дополнительного делегирующего кода",
      ],
      en: [
        "The flexibility of assembling and swapping behavior at runtime versus the indirection and the number of objects",
        "Black-box reuse through interfaces versus the conciseness of inheritance's white-box reuse",
        "Protection from the fragile base class problem versus the extra delegating code",
      ],
    },
    whenToUse: {
      ru: [
        "Поведение варьируется по нескольким независимым осям — наследование дало бы взрыв подклассов",
        "Поведение нужно менять или комбинировать в рантайме",
        "Отношение между сущностями — «has-a»/«uses-a», а не «is-a»",
      ],
      en: [
        "Behavior varies along several independent axes, where inheritance would cause a subclass explosion",
        "Behavior needs to be changed or combined at runtime",
        "The relationship between the entities is \"has-a\"/\"uses-a\", not \"is-a\"",
      ],
    },
    whenNotToUse: {
      ru: [
        "Истинное «is-a» со стабильным контрактом, где подтип соблюдает LSP, — наследование проще",
        "Фреймворк или библиотека требуют расширения своего базового класса",
      ],
      en: [
        "A genuine \"is-a\" with a stable contract where the subtype honors the LSP, where inheritance is simpler",
        "A framework or library requires you to extend its base class",
      ],
    },
    related: [
      "strategy",
      "decorator",
      "template-method",
      "lsp",
    ],
    tags: [
      "trade-offs",
      "проектирование",
    ],
  },
  {
    id: "coupling-cohesion",
    name: "Coupling & Cohesion",
    aka: [
      "Low Coupling, High Cohesion",
    ],
    category: "tradeoff",
    grade: "middle",
    tagline: {
      ru: "Слабые связи между модулями, сильные — внутри модуля",
      en: "Loose coupling between modules, strong cohesion within each one",
    },
    definition: {
      ru: "Coupling (зацепление) — степень взаимозависимости модулей: насколько изменение или использование одного требует знания внутренностей другого. Cohesion (связность) — степень, в которой элементы модуля объединены одной задачей. Классический ориентир структурного дизайна (Constantine/Yourdon, позднее у Robert C. Martin): стремиться к low coupling и high cohesion.",
      en: "Coupling is the degree of interdependence between modules: how much changing or using one requires knowing the internals of another. Cohesion is the degree to which the elements of a module are united around a single task. The classic guideline of structured design (Constantine/Yourdon, later echoed by Robert C. Martin): aim for low coupling and high cohesion.",
    },
    problem: {
      ru: "При сильном зацеплении изменение одного модуля каскадом ломает соседей: код лезет в чужие поля, знает порядок чужих вызовов, его нельзя протестировать в изоляции. При низкой связности модуль превращается в «свалку» несвязанных функций: непонятно, где искать логику и что затронет правка.",
      en: "Under tight coupling, changing one module breaks its neighbors in a cascade: the code reaches into other objects' fields, knows the order of their calls, and can't be tested in isolation. Under low cohesion, a module turns into a dumping ground of unrelated functions: it's unclear where to find the logic and what a given change will touch.",
    },
    solution: {
      ru: "Группировать код по единой ответственности, чтобы всё внутри модуля работало на одну задачу (high cohesion), а наружу выставлять узкий интерфейс, скрывая детали реализации — information hiding (low coupling). Модули общаются через абстракции и не манипулируют внутренним состоянием друг друга.",
      en: "Group code by a single responsibility so that everything inside a module serves one task (high cohesion), and expose only a narrow interface outward while hiding the implementation details — information hiding (low coupling). Modules communicate through abstractions and never manipulate one another's internal state.",
    },
    codeExample: {
      lang: "typescript",
      code: {
        ru: [
          "// High cohesion: модуль делает ровно одно — считает заказ",
          "class OrderCalculator {",
          "  subtotal(items: { price: number; qty: number }[]): number {",
          "    return items.reduce((sum, i) => sum + i.price * i.qty, 0);",
          "  }",
          "  withTax(amount: number): number {",
          "    return amount * 1.2;",
          "  }",
          "}",
          "",
          "// Low coupling: зависимость через узкий интерфейс, а не через детали SMTP",
          "interface Notifier {",
          "  send(to: string, text: string): void;",
          "}",
          "",
          "class OrderService {",
          "  constructor(private calc: OrderCalculator, private notifier: Notifier) {}",
          "  checkout(email: string, items: { price: number; qty: number }[]): void {",
          "    const total = this.calc.withTax(this.calc.subtotal(items));",
          "    this.notifier.send(email, `Итого: ${total}`); // как письмо уйдёт — не знает",
          "  }",
          "}",
        ].join('\n'),
        en: [
          "// High cohesion: the module does exactly one thing — it calculates the order",
          "class OrderCalculator {",
          "  subtotal(items: { price: number; qty: number }[]): number {",
          "    return items.reduce((sum, i) => sum + i.price * i.qty, 0);",
          "  }",
          "  withTax(amount: number): number {",
          "    return amount * 1.2;",
          "  }",
          "}",
          "",
          "// Low coupling: the dependency is a narrow interface, not the SMTP details",
          "interface Notifier {",
          "  send(to: string, text: string): void;",
          "}",
          "",
          "class OrderService {",
          "  constructor(private calc: OrderCalculator, private notifier: Notifier) {}",
          "  checkout(email: string, items: { price: number; qty: number }[]): void {",
          "    const total = this.calc.withTax(this.calc.subtotal(items));",
          "    this.notifier.send(email, `Total: ${total}`); // has no idea how the mail is sent",
          "  }",
          "}",
        ].join('\n'),
      },
    },
    pros: {
      ru: [
        "Изменения локализованы: правка внутренностей модуля не задевает соседей",
        "Модули тестируются в изоляции через подмену зависимостей",
        "Реализацию за узким интерфейсом можно заменить без правки клиентов",
        "Код читается по границам ответственности: понятно, где что искать",
      ],
      en: [
        "Changes stay localized: editing a module's internals doesn't disturb its neighbors",
        "Modules can be tested in isolation by swapping in substitute dependencies",
        "The implementation behind a narrow interface can be replaced without touching clients",
        "The code reads along its responsibility boundaries: it's clear where to look for what",
      ],
    },
    cons: {
      ru: [
        "Нулевого coupling не существует: модули обязаны как-то взаимодействовать, вопрос лишь в форме связи",
        "Чрезмерная развязка плодит интерфейсы, адаптеры и косвенность на ровном месте",
        "Границы «одной задачи» субъективны: формальных метрик недостаточно, нужно суждение о причинах изменений",
      ],
      en: [
        "Zero coupling doesn't exist: modules have to interact somehow — the only question is the form the connection takes",
        "Excessive decoupling breeds interfaces, adapters, and indirection with no real payoff",
        "The boundaries of \"one task\" are subjective: formal metrics aren't enough — you need judgment about the reasons things change",
      ],
    },
    tradeoffs: {
      ru: [
        "Явность прямых вызовов против гибкости развязки: интерфейсы и события скрывают, кто с кем на самом деле связан, и усложняют трассировку потока",
        "Агрессивное дробление ради low coupling размазывает одну задачу по модулям — coupling падает на бумаге, но падает и cohesion",
        "Развязка окупается на границах, которые реально меняются независимо, и избыточна между стабильными, всегда меняющимися вместе частями",
      ],
      en: [
        "The explicitness of direct calls versus the flexibility of decoupling: interfaces and events hide who is actually connected to whom and make the flow harder to trace",
        "Aggressive splitting for the sake of low coupling smears a single task across modules — coupling drops on paper, but so does cohesion",
        "Decoupling pays off at boundaries that genuinely change independently, and is redundant between stable parts that always change together",
      ],
    },
    whenToUse: {
      ru: [
        "Проектирование границ модулей, пакетов и сервисов: что положить вместе, что разделить",
        "Ревью кода: решение, где должна жить новая логика и не «завидует» ли класс чужим данным",
        "Оценка, готова ли часть системы к выделению в отдельный сервис или библиотеку",
      ],
      en: [
        "Designing the boundaries of modules, packages, and services: what to keep together and what to pull apart",
        "Code review: deciding where new logic should live and whether a class shows feature envy over another's data",
        "Assessing whether a part of the system is ready to be extracted into a separate service or library",
      ],
    },
    whenNotToUse: {
      ru: [
        "Одноразовые скрипты и прототипы: цена развязки не окупится",
        "Код, который всегда меняется вместе, не стоит рвать по модулям ради формально низкого coupling",
      ],
      en: [
        "One-off scripts and prototypes: the cost of decoupling won't pay for itself",
        "Code that always changes together isn't worth tearing into separate modules just for formally low coupling",
      ],
    },
    related: [
      "srp",
      "dip",
      "isp",
      "facade",
    ],
    tags: [
      "trade-offs",
      "модульность",
      "принципы",
    ],
  },
  {
    id: "dry-vs-duplication",
    name: "DRY vs Duplication",
    aka: [
      "Don't Repeat Yourself",
      "Single Source of Truth",
    ],
    category: "tradeoff",
    grade: "middle",
    tagline: {
      ru: "Устраняй дублирование знания, а не случайное сходство кода",
      en: "Eliminate duplicated knowledge, not incidental similarity in code",
    },
    definition: {
      ru: "DRY (Hunt, Thomas, «The Pragmatic Programmer»): каждый фрагмент знания должен иметь единственное, непротиворечивое, авторитетное представление в системе. Компромисс DRY vs Duplication — умение отличать дублирование знания (его устраняют) от случайного текстуального сходства кода, который лишь выглядит одинаково, но выражает разные вещи.",
      en: "DRY (Hunt and Thomas, The Pragmatic Programmer): every piece of knowledge must have a single, unambiguous, authoritative representation within the system. The DRY vs Duplication trade-off is the skill of telling duplicated knowledge (which you eliminate) apart from incidental textual similarity in code that merely looks alike but expresses different things.",
    },
    problem: {
      ru: "Скопированное бизнес-правило (ставка, лимит, формат) живёт в нескольких местах и рассинхронизируется: правило поменяли в одном месте и забыли в другом — получили тихий баг. Но слепая борьба с любым повторением рождает обратную боль: разные по смыслу куски склеиваются в общий хелпер, он обрастает флагами под каждого клиента, и правка для одного ломает других — «wrong abstraction» (Sandi Metz).",
      en: "A copied business rule (a rate, a limit, a format) lives in several places and drifts out of sync: you change the rule in one spot and forget the other, and now you have a silent bug. But blindly fighting every repetition brings the opposite pain: pieces that mean different things get glued into a shared helper, it accumulates flags for each caller, and a change for one breaks the others — the \"wrong abstraction\" (Sandi Metz).",
    },
    solution: {
      ru: "Перед устранением повторения задать вопрос: «меняются ли эти места по одной причине?». Если да — это одно знание: вынести его в единственный источник (константу, функцию, модуль). Если причины изменения разные — сходство случайно: оставить копии независимыми или подождать третьего повторения (Rule of Three, Fowler), чтобы увидеть настоящую ось обобщения.",
      en: "Before removing a repetition, ask: \"do these places change for the same reason?\" If yes, it is one piece of knowledge — extract it into a single source (a constant, a function, a module). If they change for different reasons, the similarity is incidental — keep the copies independent, or wait for the third occurrence (the Rule of Three, Fowler) to reveal the real axis of generalization.",
    },
    codeExample: {
      lang: "typescript",
      code: {
        ru: [
          "// Дублирование ЗНАНИЯ: правило «совершеннолетие = 18» живёт в двух местах.",
          "// При изменении закона одну копию поправят, вторую — забудут.",
          "function canSignContract(age: number) { return age >= 18; }",
          "function canOpenAccount(age: number) { return age >= 18; }",
          "",
          "// DRY: единственный авторитетный источник правила",
          "const ADULT_AGE = 18;",
          "const isAdult = (age: number) => age >= ADULT_AGE;",
          "function canSignContractDry(age: number) { return isAdult(age); }",
          "function canOpenAccountDry(age: number) { return isAdult(age); }",
          "",
          "// Случайное сходство — НЕ дублирование знания:",
          "// числа совпали, но меняются по разным причинам и для разных акторов.",
          "const MAX_LOGIN_LENGTH = 20; // ограничение формы регистрации (UX)",
          "const MAX_SKU_LENGTH = 20;   // требование складской системы",
          "// Слить их в одну константу — ложная абстракция:",
          "// изменение одного правила незаметно сломает другое.",
        ].join('\n'),
        en: [
          "// Duplicated KNOWLEDGE: the rule \"adulthood = 18\" lives in two places.",
          "// When the law changes, one copy gets fixed and the other is forgotten.",
          "function canSignContract(age: number) { return age >= 18; }",
          "function canOpenAccount(age: number) { return age >= 18; }",
          "",
          "// DRY: a single authoritative source for the rule",
          "const ADULT_AGE = 18;",
          "const isAdult = (age: number) => age >= ADULT_AGE;",
          "function canSignContractDry(age: number) { return isAdult(age); }",
          "function canOpenAccountDry(age: number) { return isAdult(age); }",
          "",
          "// Incidental similarity — NOT duplicated knowledge:",
          "// the numbers happen to match, but they change for different reasons and different actors.",
          "const MAX_LOGIN_LENGTH = 20; // registration-form limit (UX)",
          "const MAX_SKU_LENGTH = 20;   // requirement of the warehouse system",
          "// Merging them into one constant is a false abstraction:",
          "// changing one rule would silently break the other.",
        ].join('\n'),
      },
    },
    pros: {
      ru: [
        "Правило меняется ровно в одном месте — исключена рассинхронизация копий",
        "Одна и та же ошибка не размножается по кодовой базе, меньше кода на ревью",
        "Явно выделенное знание (именованная константа, функция) само документирует замысел",
      ],
      en: [
        "The rule changes in exactly one place — copies can no longer drift out of sync",
        "The same bug does not multiply across the codebase, and there is less code to review",
        "Knowledge made explicit (a named constant or function) documents the intent by itself",
      ],
    },
    cons: {
      ru: [
        "Чрезмерный DRY склеивает случайно похожий код в ложную абстракцию",
        "Общий код связывает всех клиентов: правка ради одного рискует сломать остальных",
        "Универсальные хелперы обрастают флагами и параметрами-переключателями под каждого потребителя",
      ],
      en: [
        "Excessive DRY glues incidentally similar code into a false abstraction",
        "Shared code couples all callers: a change made for one risks breaking the rest",
        "Catch-all helpers accumulate flags and toggle parameters to serve every consumer",
      ],
    },
    tradeoffs: {
      ru: [
        "Единый источник знания против связывания независимых клиентов общим кодом",
        "Раннее обобщение экономит строки сейчас, но неверная абстракция дороже дублирования (Sandi Metz: «duplication is far cheaper than the wrong abstraction»)",
        "Rule of Three: терпим вторую копию, чтобы третье повторение показало настоящую ось обобщения",
      ],
      en: [
        "A single source of knowledge versus coupling independent callers through shared code",
        "Early generalization saves lines now, but the wrong abstraction costs more than duplication (Sandi Metz: \"duplication is far cheaper than the wrong abstraction\")",
        "Rule of Three: tolerate the second copy so that the third occurrence reveals the real axis of generalization",
      ],
    },
    whenToUse: {
      ru: [
        "Копии выражают одно и то же знание: бизнес-правило, инвариант, формат данных",
        "Любое изменение требует синхронной правки всех копий — забытая копия означает баг",
        "Повторение подтвердилось несколько раз и ось обобщения очевидна (Rule of Three)",
      ],
      en: [
        "The copies express the same piece of knowledge: a business rule, an invariant, a data format",
        "Any change requires updating all copies in sync — a forgotten copy means a bug",
        "The repetition has recurred several times and the axis of generalization is obvious (Rule of Three)",
      ],
    },
    whenNotToUse: {
      ru: [
        "Код похож текстуально, но фрагменты меняются по разным причинам и для разных акторов",
        "Обобщение требует флагов и ветвлений под каждого клиента — признак ложной абстракции",
        "Совпали куски двух независимых модулей/доменов — общий хелпер свяжет их лишней зависимостью",
      ],
      en: [
        "The code looks textually similar, but the fragments change for different reasons and different actors",
        "Generalizing it requires flags and branches for each caller — a sign of a false abstraction",
        "Fragments of two independent modules/domains happen to match — a shared helper would tie them together with a needless dependency",
      ],
    },
    related: [
      "srp",
      "abstraction-cost",
      "yagni-vs-flexibility",
      "coupling-cohesion",
    ],
    tags: [
      "компромиссы",
      "принципы",
    ],
  },
  {
    id: "abstraction-cost",
    name: "Abstraction Cost",
    aka: [
      "Cost of Abstraction",
    ],
    category: "tradeoff",
    grade: "senior",
    tagline: {
      ru: "Каждый слой косвенности нужно окупить — абстракция не бывает бесплатной",
      en: "Every layer of indirection has to earn its keep — abstraction is never free",
    },
    definition: {
      ru: "Любая абстракция имеет цену: дополнительный слой косвенности (indirection), рост когнитивной нагрузки при чтении и отладке, а также риск «протечки» скрытых деталей (Law of Leaky Abstractions, Joel Spolsky). Абстракция оправдана только тогда, когда выгода от развязки и сокрытия деталей превышает эту цену.",
      en: "Every abstraction has a cost: an extra layer of indirection, higher cognitive load when reading and debugging, and the risk that hidden details leak through (the Law of Leaky Abstractions, Joel Spolsky). An abstraction is justified only when the benefit of decoupling and hiding details outweighs that cost.",
    },
    problem: {
      ru: "Разработчики вводят интерфейсы, фабрики и обёртки «на всякий случай» — под гибкость, которая никогда не понадобится. В результате простая операция размазывается по нескольким слоям: чтобы понять одну строку логики, приходится прыгать через интерфейс, фабрику и реализацию. Неудачная абстракция ещё хуже: как отмечает Sandi Metz, дублирование дешевле, чем неправильная абстракция (the wrong abstraction), потому что её потом дорого выкорчёвывать.",
      en: "Developers introduce interfaces, factories, and wrappers \"just in case\" — for flexibility that will never be needed. As a result, a simple operation gets smeared across several layers: to understand a single line of logic you have to hop through an interface, a factory, and an implementation. A bad abstraction is even worse: as Sandi Metz points out, duplication is cheaper than the wrong abstraction, because ripping it out later is expensive.",
    },
    solution: {
      ru: "Относиться к абстракции как к инвестиции: вводить её, когда есть реальная вторая реализация или подтверждённая ось изменений, а не гипотетическая. Начинать с самого простого работающего кода, применять «правило трёх» перед обобщением и регулярно проверять, что каждый слой по-прежнему окупает свою косвенность. Помнить, что абстракции протекают: скрытые детали (сеть, хранилище, кодировки) всё равно всплывают при отладке и настройке производительности.",
      en: "Treat abstraction as an investment: introduce it when there is a real second implementation or a proven axis of change, not a hypothetical one. Start with the simplest code that works, apply the rule of three before generalizing, and regularly check that each layer still earns its indirection. Remember that abstractions leak: hidden details (the network, storage, encodings) surface anyway during debugging and performance tuning.",
    },
    codeExample: {
      lang: "typescript",
      code: {
        ru: [
          "// Прямой вариант: нулевая цена косвенности, но жёсткая привязка к localStorage",
          "function saveUserDirect(user: { id: string }) {",
          "  localStorage.setItem(`user:${user.id}`, JSON.stringify(user));",
          "}",
          "",
          "// Абстракция: развязывает код от хранилища, но той же строке логики",
          "// теперь нужны интерфейс, реализация и внедрение зависимости",
          "interface KeyValueStore {",
          "  set(key: string, value: string): void;",
          "}",
          "",
          "class LocalStore implements KeyValueStore {",
          "  set(key: string, value: string) { localStorage.setItem(key, value); }",
          "}",
          "",
          "class UserRepository {",
          "  constructor(private store: KeyValueStore) {} // цена: три слоя вместо одной функции",
          "  save(user: { id: string }) {",
          "    this.store.set(`user:${user.id}`, JSON.stringify(user));",
          "  }",
          "}",
          "",
          "// Окупается, только если реализаций реально несколько:",
          "const repo = new UserRepository(new LocalStore()); // в тестах — InMemoryStore",
          "repo.save({ id: '42' });",
        ].join('\n'),
        en: [
          "// Direct version: zero indirection cost, but hard-wired to localStorage",
          "function saveUserDirect(user: { id: string }) {",
          "  localStorage.setItem(`user:${user.id}`, JSON.stringify(user));",
          "}",
          "",
          "// Abstraction: decouples the code from storage, but that same line of logic",
          "// now needs an interface, an implementation, and dependency injection",
          "interface KeyValueStore {",
          "  set(key: string, value: string): void;",
          "}",
          "",
          "class LocalStore implements KeyValueStore {",
          "  set(key: string, value: string) { localStorage.setItem(key, value); }",
          "}",
          "",
          "class UserRepository {",
          "  constructor(private store: KeyValueStore) {} // cost: three layers instead of one function",
          "  save(user: { id: string }) {",
          "    this.store.set(`user:${user.id}`, JSON.stringify(user));",
          "  }",
          "}",
          "",
          "// Pays off only if there really are multiple implementations:",
          "const repo = new UserRepository(new LocalStore()); // in tests — InMemoryStore",
          "repo.save({ id: '42' });",
        ].join('\n'),
      },
    },
    pros: {
      ru: [
        "Скрывает детали реализации и снижает связанность модулей",
        "Даёт точку подмены: тестовые дублёры, альтернативные реализации",
        "Локализует будущие изменения за стабильным интерфейсом",
      ],
      en: [
        "Hides implementation details and reduces coupling between modules",
        "Provides a substitution point: test doubles, alternative implementations",
        "Localizes future changes behind a stable interface",
      ],
    },
    cons: {
      ru: [
        "Каждый слой косвенности удлиняет путь чтения и отладки кода",
        "Абстракции протекают: скрытые детали всплывают в производительности и ошибках",
        "Неправильная абстракция закрепляет неверную модель и дорого исправляется",
        "Спекулятивная общность (speculative generality) — код под сценарии, которых не будет",
      ],
      en: [
        "Every layer of indirection lengthens the path of reading and debugging the code",
        "Abstractions leak: hidden details surface in performance and bugs",
        "The wrong abstraction locks in a flawed model and is expensive to fix",
        "Speculative generality — code for scenarios that will never happen",
      ],
    },
    tradeoffs: {
      ru: [
        "Гибкость и развязка против косвенности и когнитивной нагрузки",
        "Сокрытие деталей против прозрачности при отладке и оптимизации",
        "Ранняя абстракция «на вырост» против дешёвого прямого кода, который легко переписать",
      ],
      en: [
        "Flexibility and decoupling vs. indirection and cognitive load",
        "Hiding details vs. transparency during debugging and optimization",
        "Early abstraction built for future growth vs. cheap direct code that is easy to rewrite",
      ],
    },
    whenToUse: {
      ru: [
        "Есть реальная вторая реализация или подтверждённая ось изменений",
        "Нужна точка подмены для тестирования внешней зависимости",
        "Деталь реализации (SDK, протокол, хранилище) нестабильна и не должна расползаться по коду",
      ],
      en: [
        "There is a real second implementation or a proven axis of change",
        "You need a substitution point for testing an external dependency",
        "An implementation detail (an SDK, protocol, or storage) is unstable and must not spread throughout the code",
      ],
    },
    whenNotToUse: {
      ru: [
        "Реализация одна, тривиальна и вряд ли изменится — прямой код дешевле",
        "Абстракция вводится «на всякий случай» под гипотетическую гибкость",
        "Обобщение делается по первому совпадению, а не по устойчивой закономерности",
      ],
      en: [
        "There is a single implementation, it is trivial, and unlikely to change — direct code is cheaper",
        "The abstraction is introduced \"just in case\" for hypothetical flexibility",
        "Generalization is done on the first match rather than on a stable pattern",
      ],
    },
    related: [
      "yagni-vs-flexibility",
      "dip",
      "coupling-cohesion",
      "dry-vs-duplication",
    ],
    tags: [
      "trade-offs",
      "абстракция",
      "косвенность",
      "leaky abstractions",
    ],
  },
  {
    id: "yagni-vs-flexibility",
    name: "YAGNI vs Flexibility",
    aka: [
      "You Aren't Gonna Need It",
    ],
    category: "tradeoff",
    grade: "senior",
    tagline: {
      ru: "Не строй гибкость под требования, которых ещё нет",
      en: "Don't build flexibility for requirements that don't exist yet",
    },
    definition: {
      ru: "YAGNI (You Aren't Gonna Need It) — принцип экстремального программирования (Kent Beck, Ron Jeffries; развит в эссе Fowler «Yagni»): не реализуй функциональность и точки расширения, пока они реально не понадобились. Компромисс — между стоимостью спекулятивной гибкости, которую платишь сейчас, и стоимостью рефакторинга потом, если требование всё-таки появится.",
      en: "YAGNI (You Aren't Gonna Need It) is an Extreme Programming principle (Kent Beck, Ron Jeffries; developed in Fowler's essay \"Yagni\"): don't implement functionality or extension points until you actually need them. The trade-off is between the cost of speculative flexibility you pay for now and the cost of refactoring later if the requirement does eventually arrive.",
    },
    problem: {
      ru: "Команды закладывают «гибкость на вырост»: лишние интерфейсы, слои, реестры и конфигурацию под гипотетические будущие требования. Эта спекулятивная общность (Fowler: speculative generality) стоит денег уже сегодня — её пишут, тестируют, читают и сопровождают, — а предсказанные требования часто не наступают вовсе или приходят в другой форме, и построенная абстракция оказывается не на той оси изменчивости.",
      en: "Teams build in \"flexibility to grow into\": extra interfaces, layers, registries, and configuration for hypothetical future requirements. This speculative generality (Fowler's term) costs money today — it has to be written, tested, read, and maintained — while the predicted requirements often never materialize at all, or arrive in a different form, leaving the abstraction built on the wrong axis of change.",
    },
    solution: {
      ru: "Реализуем простейшее решение, покрывающее текущие требования, и держим код дешёвым для изменения (тесты, регулярный рефакторинг). Точку расширения вводим в момент появления второго реального случая: тогда ось изменчивости известна по фактам, и абстракция строится под настоящие требования, а не под догадки. Гибкость покупается не заранее, а тогда, когда за неё есть чем платить.",
      en: "Implement the simplest solution that covers today's requirements, and keep the code cheap to change (tests, regular refactoring). Introduce an extension point the moment a second real case appears: by then the axis of change is known from facts, and the abstraction is built for actual requirements rather than guesses. You buy flexibility not up front, but when there's a concrete requirement that justifies the cost.",
    },
    codeExample: {
      lang: "typescript",
      code: {
        ru: [
          "// Спекулятивная гибкость: интерфейсы «на будущее» при единственной реализации",
          "interface ReportSource { fetch(): string[][]; }",
          "interface ReportFormatter { format(rows: string[][]): string; }",
          "",
          "class CsvFormatter implements ReportFormatter {",
          "  format(rows: string[][]) { return rows.map((r) => r.join(',')).join('\\n'); }",
          "}",
          "class ArraySource implements ReportSource {",
          "  constructor(private rows: string[][]) {}",
          "  fetch() { return this.rows; }",
          "}",
          "class ReportEngine {",
          "  constructor(private source: ReportSource, private formatter: ReportFormatter) {}",
          "  build() { return this.formatter.format(this.source.fetch()); }",
          "}",
          "",
          "// YAGNI: требование сегодня — ровно один отчёт, CSV из готовых строк",
          "function buildCsvReport(rows: string[][]): string {",
          "  return rows.map((r) => r.join(',')).join('\\n');",
          "}",
          "// Точку расширения добавим при втором реальном формате — ось изменчивости станет известна",
        ].join('\n'),
        en: [
          "// Speculative flexibility: \"future-proof\" interfaces with only a single implementation",
          "interface ReportSource { fetch(): string[][]; }",
          "interface ReportFormatter { format(rows: string[][]): string; }",
          "",
          "class CsvFormatter implements ReportFormatter {",
          "  format(rows: string[][]) { return rows.map((r) => r.join(',')).join('\\n'); }",
          "}",
          "class ArraySource implements ReportSource {",
          "  constructor(private rows: string[][]) {}",
          "  fetch() { return this.rows; }",
          "}",
          "class ReportEngine {",
          "  constructor(private source: ReportSource, private formatter: ReportFormatter) {}",
          "  build() { return this.formatter.format(this.source.fetch()); }",
          "}",
          "",
          "// YAGNI: today's requirement is exactly one report — CSV from ready-made rows",
          "function buildCsvReport(rows: string[][]): string {",
          "  return rows.map((r) => r.join(',')).join('\\n');",
          "}",
          "// Add the extension point when a second real format appears — the axis of change will then be known",
        ].join('\n'),
      },
    },
    pros: {
      ru: [
        "Меньше кода сейчас — ниже стоимость написания, чтения, тестирования и сопровождения",
        "Абстракции строятся по реальным осям изменчивости, а не по угаданным",
        "Быстрее поставка текущей ценности: усилия не уходят на неиспользуемую гибкость",
      ],
      en: [
        "Less code now — a lower cost to write, read, test, and maintain",
        "Abstractions are built along real axes of change, not guessed ones",
        "Faster delivery of current value: effort isn't spent on unused flexibility",
      ],
    },
    cons: {
      ru: [
        "Если требование всё же придёт, понадобится рефакторинг, а иногда и миграция данных или API",
        "Требует дисциплины: без тестов и регулярного рефакторинга «простой» код быстро костенеет",
        "Легко перепутать YAGNI с отказом от проектирования вообще и наплодить хаос вместо простоты",
      ],
      en: [
        "If the requirement does arrive, you'll need to refactor — and sometimes migrate data or an API",
        "It demands discipline: without tests and regular refactoring, \"simple\" code quickly ossifies",
        "It's easy to mistake YAGNI for abandoning design altogether and breed chaos instead of simplicity",
      ],
    },
    tradeoffs: {
      ru: [
        "Стоимость лишней гибкости сегодня против стоимости рефакторинга завтра",
        "Скорость поставки текущих требований против готовности к гипотетическим будущим",
        "YAGNI работает только в паре с дешёвым изменением кода: чем слабее тесты и практики рефакторинга, тем дороже откладывать гибкость",
      ],
      en: [
        "The cost of extra flexibility today versus the cost of refactoring tomorrow",
        "The speed of delivering current requirements versus readiness for hypothetical future ones",
        "YAGNI only works paired with cheap-to-change code: the weaker your tests and refactoring practices, the more expensive it is to defer flexibility",
      ],
    },
    whenToUse: {
      ru: [
        "Прикладной код с быстрым циклом изменений и хорошим тестовым покрытием",
        "Будущие требования — гипотезы и «а вдруг понадобится», а не подтверждённые планы",
        "Есть соблазн добавить параметр, слой или реестр «на всякий случай» при единственном реальном сценарии",
      ],
      en: [
        "Application code with a fast change cycle and good test coverage",
        "Future requirements are hypotheses and \"just in case\" guesses, not confirmed plans",
        "You're tempted to add a parameter, layer, or registry \"just in case\" when there's only one real scenario",
      ],
    },
    whenNotToUse: {
      ru: [
        "Публичные API, протоколы и схемы БД: менять их после публикации дорого, расширяемость стоит продумать заранее",
        "Требование подтверждено и запланировано на ближайшие итерации — это уже не спекуляция, а известная ось изменчивости",
      ],
      en: [
        "Public APIs, protocols, and database schemas: changing them after release is expensive, so extensibility is worth thinking through up front",
        "The requirement is confirmed and scheduled for upcoming iterations — that's no longer speculation but a known axis of change",
      ],
    },
    related: [
      "abstraction-cost",
      "ocp",
      "dry-vs-duplication",
      "strategy",
    ],
    tags: [
      "компромиссы",
      "принципы",
      "XP",
    ],
  },
  {
    id: "performance-vs-readability",
    name: "Performance vs Readability",
    aka: [
      "Premature Optimization",
    ],
    category: "tradeoff",
    grade: "lead",
    tagline: {
      ru: "Скорость выполнения кода против скорости его понимания: оптимизируй по измерениям, а не по интуиции",
      en: "How fast the code runs versus how fast it can be understood: optimize by measurement, not by intuition",
    },
    definition: {
      ru: "Компромисс между временем выполнения кода и стоимостью его понимания и сопровождения. Оптимизации (ручные циклы, кэши, предвыделенные буферы, денормализация) почти всегда усложняют код, поэтому по умолчанию выбирается читаемость, а производительность повышается точечно — на измеренных горячих путях. Классическая формулировка у Knuth: «premature optimization is the root of all evil» — примерно в 97% случаев о мелких эффективностях стоит забыть, но в критичных 3% оптимизация обязательна.",
      en: "A trade-off between how fast code runs and the cost of understanding and maintaining it. Optimizations (hand-rolled loops, caches, preallocated buffers, denormalization) almost always make code more complex, so readability is the default and performance is raised selectively — on measured hot paths. Knuth's classic formulation is \"premature optimization is the root of all evil\": in roughly 97% of cases small efficiencies should be forgotten, but in the critical 3% optimization is essential.",
    },
    problem: {
      ru: "Разработчики «оптимизируют» код по интуиции: заранее переписывают участки в нечитаемом стиле, хотя реальные узкие места обычно лежат в другом (I/O, сеть, алгоритмическая сложность, лишние запросы к БД). Интуиция о том, где программа тратит время, систематически ошибается. Результат — код, который трудно читать, менять и ревьюить, при почти нулевом выигрыше в скорости; а настоящие узкие места остаются нетронутыми.",
      en: "Developers \"optimize\" code on intuition: they rewrite sections in an unreadable style ahead of time, even though the real bottlenecks usually lie elsewhere (I/O, the network, algorithmic complexity, redundant database queries). Intuition about where a program spends its time is systematically wrong. The result is code that is hard to read, change, and review, with almost no gain in speed — while the real bottlenecks are left untouched.",
    },
    solution: {
      ru: "Сначала пишется ясный код (Kent Beck: «make it work, make it right, make it fast»). Затем профилировщик и метрики показывают реальные горячие точки — как правило, это малая доля кодовой базы. Только их оптимизируют: ускоренный код изолируют за понятным интерфейсом, покрывают тестами и сопровождают комментарием с причиной и цифрами бенчмарка, чтобы нечитаемость не расползалась по системе и была защитима перед ревьюером.",
      en: "First write clear code (Kent Beck: \"make it work, make it right, make it fast\"). Then a profiler and metrics reveal the real hot spots — typically a small fraction of the codebase. Only those are optimized: the sped-up code is isolated behind a clear interface, covered by tests, and accompanied by a comment giving the reason and the benchmark numbers, so that unreadability doesn't spread through the system and stays defensible to a reviewer.",
    },
    codeExample: {
      lang: "typescript",
      code: {
        ru: [
          "interface Order { status: 'paid' | 'pending'; amount: number; }",
          "",
          "// По умолчанию: читаемая версия — намерение видно с первого взгляда",
          "function totalPaid(orders: Order[]): number {",
          "  return orders",
          "    .filter((o) => o.status === 'paid')",
          "    .reduce((sum, o) => sum + o.amount, 0);",
          "}",
          "",
          "// Горячий путь (миллионы заказов, подтверждено профилировщиком):",
          "// один проход без промежуточных массивов. Оптимизация изолирована",
          "// за той же сигнатурой и задокументирована: бенчмарк ~3x на 1M элементов.",
          "function totalPaidHot(orders: Order[]): number {",
          "  let sum = 0;",
          "  for (let i = 0; i < orders.length; i++) {",
          "    const o = orders[i];",
          "    if (o.status === 'paid') sum += o.amount;",
          "  }",
          "  return sum;",
          "}",
        ].join('\n'),
        en: [
          "interface Order { status: 'paid' | 'pending'; amount: number; }",
          "",
          "// Default: the readable version — the intent is obvious at a glance",
          "function totalPaid(orders: Order[]): number {",
          "  return orders",
          "    .filter((o) => o.status === 'paid')",
          "    .reduce((sum, o) => sum + o.amount, 0);",
          "}",
          "",
          "// Hot path (millions of orders, confirmed by the profiler):",
          "// a single pass with no intermediate arrays. The optimization is isolated",
          "// behind the same signature and documented: benchmark ~3x on 1M elements.",
          "function totalPaidHot(orders: Order[]): number {",
          "  let sum = 0;",
          "  for (let i = 0; i < orders.length; i++) {",
          "    const o = orders[i];",
          "    if (o.status === 'paid') sum += o.amount;",
          "  }",
          "  return sum;",
          "}",
        ].join('\n'),
      },
    },
    pros: {
      ru: [
        "Основная часть кодовой базы остаётся простой и дешёвой в сопровождении",
        "Усилия по оптимизации попадают в реальные узкие места, подтверждённые профилировщиком, а не в предполагаемые",
        "Оптимизированный код изолирован и задокументирован — понятно, почему он написан именно так и когда его можно упростить обратно",
      ],
      en: [
        "The bulk of the codebase stays simple and cheap to maintain",
        "Optimization effort goes into real bottlenecks confirmed by the profiler, not assumed ones",
        "The optimized code is isolated and documented — it's clear why it was written this way and when it can be simplified back",
      ],
    },
    cons: {
      ru: [
        "Требует инфраструктуры измерений: профилировщик, бенчмарки, метрики в production",
        "Отложенная оптимизация несёт риск: архитектурно значимые решения (структуры данных, схема БД, границы сервисов) дорого менять постфактум",
        "«Сначала читаемость» не спасает от алгоритмически плохих решений — O(n²) на больших данных не лечится микрооптимизациями",
      ],
      en: [
        "Requires measurement infrastructure: a profiler, benchmarks, and production metrics",
        "Deferring optimization carries a risk: architecturally significant decisions (data structures, database schema, service boundaries) are expensive to change after the fact",
        "\"Readability first\" won't save you from algorithmically bad choices — O(n²) on large data isn't cured by micro-optimizations",
      ],
    },
    tradeoffs: {
      ru: [
        "Скорость выполнения против скорости понимания и изменения кода",
        "Ранний выбор производительной архитектуры в значимых местах против преждевременной оптимизации всего подряд",
        "Локальный выигрыш горячего пути против роста общей сложности кодовой базы",
      ],
      en: [
        "Execution speed versus the speed of understanding and changing the code",
        "Choosing a performant architecture early where it matters versus prematurely optimizing everything in sight",
        "A local hot-path win versus the growth of overall codebase complexity",
      ],
    },
    whenToUse: {
      ru: [
        "Профилировщик показал горячий путь, и его вклад в задержку подтверждён цифрами",
        "Есть явные требования к производительности: SLA, real-time, игровой цикл, обработка больших объёмов данных",
        "Оптимизацию можно изолировать за понятным интерфейсом и зафиксировать бенчмарком и тестами",
      ],
      en: [
        "The profiler has surfaced a hot path and its contribution to latency is confirmed by numbers",
        "There are explicit performance requirements: an SLA, real-time, a game loop, or processing large volumes of data",
        "The optimization can be isolated behind a clear interface and pinned down with a benchmark and tests",
      ],
    },
    whenNotToUse: {
      ru: [
        "Код выполняется редко или вне горячего пути — выигрыш не окупит потерю читаемости",
        "Узкое место не измерено: интуиция о производительности систематически ошибается",
        "Проблема алгоритмическая (неподходящая структура данных, лишние запросы) — сначала меняют алгоритм, а не микрооптимизируют строки",
      ],
      en: [
        "The code runs rarely or off the hot path — the gain won't pay for the lost readability",
        "The bottleneck hasn't been measured: intuition about performance is systematically wrong",
        "The problem is algorithmic (the wrong data structure, redundant queries) — change the algorithm first rather than micro-optimizing individual lines",
      ],
    },
    related: [
      "abstraction-cost",
      "yagni-vs-flexibility",
      "dry-vs-duplication",
    ],
    tags: [
      "trade-offs",
      "производительность",
      "читаемость",
    ],
  },
];

export const tradeoffsQuestions: Question[] = [
  {
    id: "t-composition-vs-inheritance-1",
    type: "tradeoff",
    category: "tradeoff",
    grade: "middle",
    prompt: {
      ru: "В чём суть компромисса «composition vs inheritance»?",
      en: "What is the essence of the composition vs inheritance trade-off?",
    },
    options: {
      ru: [
        "Наследование всегда быстрее композиции, потому что вызовы не проходят через делегирование",
        "Композиция полностью заменяет наследование, поэтому extends в современном коде — всегда ошибка",
        "Композиция даёт гибкую сборку и замену поведения в рантайме ценой делегирования и большего числа объектов; наследование лаконичнее для истинного «is-a», но фиксирует связь при компиляции и завязывает подкласс на детали родителя",
        "Разница чисто синтаксическая: extends и приватное поле с объектом дают одинаковую связанность",
      ],
      en: [
        "Inheritance is always faster than composition because calls don't go through delegation",
        "Composition fully replaces inheritance, so extends in modern code is always a mistake",
        "Composition offers flexible assembly and runtime swapping of behavior at the cost of delegation and more objects; inheritance is more concise for a genuine \"is-a\" but fixes the relationship at compile time and binds the subclass to the parent's internals",
        "The difference is purely syntactic: extends and a private field holding an object yield the same coupling",
      ],
    },
    correctIndex: 2,
    explanation: {
      ru: "Верен третий вариант: это и есть компромисс из GoF («favor object composition over class inheritance») — композиция переиспользует «чёрным ящиком» через интерфейсы и позволяет менять части в рантайме, но добавляет объекты и делегирующий код; наследование короче для настоящего «is-a», но связь задаётся при компиляции, а подкласс зависит от реализации родителя (fragile base class). Первый вариант неверен: разница в скорости вызовов на практике ничтожна и сутью компромисса не является. Второй неверен: GoF рекомендуют предпочитать композицию, а не запрещают наследование — для стабильного «is-a» с соблюдением LSP оно уместно. Четвёртый неверен: связанность принципиально разная — extends открывает подклассу protected-детали и переопределение (белый ящик), композиция ограничивает зависимость публичным интерфейсом части.",
      en: "The third option is correct: this is exactly the GoF trade-off (\"favor object composition over class inheritance\"). Composition reuses code black-box through interfaces and lets you swap parts at runtime, but it adds objects and delegating code; inheritance is shorter for a true \"is-a\", but the relationship is set at compile time and the subclass depends on the parent's implementation (the fragile base class problem). The first option is wrong: the difference in call speed is negligible in practice and is not the point of the trade-off. The second is wrong: GoF recommend preferring composition, not banning inheritance; for a stable \"is-a\" that honors the LSP it is appropriate. The fourth is wrong: the coupling is fundamentally different: extends exposes protected internals and overriding to the subclass (white-box), whereas composition confines the dependency to the part's public interface.",
    },
    conceptId: "composition-vs-inheritance",
  },
  {
    id: "cs-composition-vs-inheritance-1",
    type: "code-smell",
    category: "tradeoff",
    grade: "middle",
    prompt: {
      ru: "Что не так в этом коде и как его улучшить?",
      en: "What's wrong with this code, and how would you improve it?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "class Stack<T> extends Array<T> {",
          "  peek(): T | undefined { return this[this.length - 1]; }",
          "}",
          "",
          "const s = new Stack<number>();",
          "s.push(1);",
          "s.push(2);",
          "s.unshift(0); // унаследовано от Array: элемент вставлен в «дно» стека",
          "s.splice(0, 2); // инвариант LIFO разрушен снаружи класса",
        ].join('\n'),
        en: [
          "class Stack<T> extends Array<T> {",
          "  peek(): T | undefined { return this[this.length - 1]; }",
          "}",
          "",
          "const s = new Stack<number>();",
          "s.push(1);",
          "s.push(2);",
          "s.unshift(0); // inherited from Array: the element is inserted at the \"bottom\" of the stack",
          "s.splice(0, 2); // the LIFO invariant is broken from outside the class",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "Проблема только в peek: при пустом стеке он возвращает undefined вместо исключения",
        "Наследование использовано ради переиспользования кода без отношения «is-a»: Stack получает весь API массива, и unshift/splice ломают инвариант LIFO — лучше хранить массив в приватном поле и открыть только push/pop/peek (композиция)",
        "Stack нужно сделать синглтоном, чтобы никто не создавал второй экземпляр и не портил данные",
        "Достаточно переопределить unshift и splice так, чтобы они бросали исключение, — наследование здесь уместно",
      ],
      en: [
        "The only problem is peek: on an empty stack it returns undefined instead of throwing",
        "Inheritance is used purely for code reuse without an \"is-a\" relationship: Stack inherits the entire array API, and unshift/splice break the LIFO invariant. Better to hold the array in a private field and expose only push/pop/peek (composition)",
        "Stack should be made a singleton so nobody creates a second instance and corrupts the data",
        "It's enough to override unshift and splice so they throw; inheritance is appropriate here",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "Верен второй вариант: стек — не «разновидность массива», а структура с инвариантом LIFO; extends открывает клиентам весь API Array (unshift, splice, индексацию), и инвариант можно разрушить снаружи. Композиция — приватное поле с массивом и узкий публичный интерфейс push/pop/peek — переиспользует код массива, не наследуя его контракт. Первый вариант неверен: возврат undefined — вопрос дизайна API, он не устраняет главную дыру в инкапсуляции. Третий неверен: Singleton ограничивает число экземпляров и никак не защищает инвариант каждого из них. Четвёртый неверен: переопределение «лишних» методов исключениями сужает контракт базового типа и нарушает LSP — Stack перестаёт подставляться там, где ожидают Array; это симптом того, что «is-a» здесь ложное и наследование выбрано ошибочно.",
      en: "The second option is correct: a stack is not \"a kind of array\" but a structure with a LIFO invariant; extends exposes the entire Array API (unshift, splice, indexing) to clients, and the invariant can be broken from outside. Composition, a private array field with a narrow public interface of push/pop/peek, reuses the array's code without inheriting its contract. The first option is wrong: returning undefined is an API-design question and doesn't close the main hole in encapsulation. The third is wrong: a Singleton limits the number of instances and does nothing to protect each instance's invariant. The fourth is wrong: overriding the \"extra\" methods to throw narrows the base type's contract and violates the LSP, so Stack can no longer be substituted where an Array is expected; this is a symptom that the \"is-a\" here is false and inheritance was chosen by mistake.",
    },
    conceptId: "composition-vs-inheritance",
  },
  {
    id: "t-coupling-cohesion-1",
    type: "tradeoff",
    category: "tradeoff",
    grade: "middle",
    prompt: {
      ru: "Команда решила снизить зацепление (coupling) между модулями, переведя все взаимодействия на интерфейсы и события. В чём компромисс такого решения?",
      en: "A team decided to reduce coupling between modules by routing every interaction through interfaces and events. What is the trade-off of that decision?",
    },
    options: {
      ru: [
        "Компромисса нет: чем ниже coupling, тем лучше дизайн во всех случаях",
        "Связи не исчезают, а становятся менее явными: растёт косвенность, и чрезмерное дробление может размазать одну задачу по модулям, снизив cohesion",
        "Интерфейсы и события заметно замедляют выполнение, поэтому развязка оправдана только в высоконагруженных системах",
        "Низкое зацепление требует объединить взаимодействующие модули в один, пожертвовав размером класса",
      ],
      en: [
        "There is no trade-off: the lower the coupling, the better the design in every case",
        "The dependencies don't disappear, they just become less explicit: indirection grows, and excessive splitting can smear a single task across modules, lowering cohesion",
        "Interfaces and events noticeably slow execution down, so decoupling is justified only in high-load systems",
        "Low coupling requires merging the interacting modules into one, at the cost of class size",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "Верен второй вариант: развязка не убирает зависимости, а меняет их форму — прямой вызов превращается в интерфейс или событие, поток управления становится труднее проследить, а если ради «низкого coupling» порезать код, который всегда меняется вместе, одна задача расползётся по модулям и cohesion упадёт. Первый вариант неверен: low coupling — ориентир, а не абсолют; между стабильными, совместно меняющимися частями развязка избыточна. Третий неверен: цена вопроса — читаемость и косвенность, а не производительность; накладные расходы полиморфизма и событий почти всегда пренебрежимы. Четвёртый неверен: слияние модулей — противоположность идее, оно создаёт модуль-«свалку» с низкой связностью, а не снижает зацепление.",
      en: "The second option is correct: decoupling doesn't remove dependencies, it changes their form — a direct call becomes an interface or an event, the control flow gets harder to trace, and if you carve up code that always changes together for the sake of \"low coupling,\" a single task ends up scattered across modules and cohesion drops. The first option is wrong: low coupling is a guideline, not an absolute — between stable parts that change together, decoupling is redundant. The third is wrong: the price here is readability and indirection, not performance — the overhead of polymorphism and events is almost always negligible. The fourth is wrong: merging modules is the opposite of the idea — it creates a low-cohesion dumping-ground module rather than reducing coupling.",
    },
    conceptId: "coupling-cohesion",
  },
  {
    id: "cs-coupling-cohesion-1",
    type: "code-smell",
    category: "tradeoff",
    grade: "middle",
    prompt: {
      ru: "Что не так с этим кодом с точки зрения coupling и cohesion, и как его улучшить?",
      en: "What's wrong with this code from a coupling and cohesion standpoint, and how would you improve it?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "class EmailSender {",
          "  host = 'smtp.local';",
          "  connected = false;",
          "  connect() { this.connected = true; }",
          "  push(raw: string) { /* низкоуровневая отправка */ }",
          "}",
          "",
          "class ReportService {",
          "  send(report: string) {",
          "    const sender = new EmailSender();",
          "    sender.host = 'smtp.prod';        // лезем во внутренности",
          "    sender.connect();                 // знаем порядок чужих шагов",
          "    if (sender.connected) {",
          "      sender.push('From: reports\\n' + report); // собираем чужой протокол",
          "    }",
          "  }",
          "}",
        ].join('\n'),
        en: [
          "class EmailSender {",
          "  host = 'smtp.local';",
          "  connected = false;",
          "  connect() { this.connected = true; }",
          "  push(raw: string) { /* low-level send */ }",
          "}",
          "",
          "class ReportService {",
          "  send(report: string) {",
          "    const sender = new EmailSender();",
          "    sender.host = 'smtp.prod';        // reaching into its internals",
          "    sender.connect();                 // depending on another's step order",
          "    if (sender.connected) {",
          "      sender.push('From: reports\\n' + report); // reassembling another's protocol",
          "    }",
          "  }",
          "}",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "ReportService жёстко зацеплен за внутренности EmailSender: сам создаёт его, правит поля и повторяет протокол отправки — нужно скрыть эти шаги внутри EmailSender и зависеть от узкого интерфейса вроде send(to, text)",
        "Проблема в низкой связности EmailSender: методы connect и push надо разнести по двум разным классам",
        "Главная ошибка — строковая конкатенация: с шаблонными литералами вместо '+' зацепление исчезнет",
        "Код нарушает LSP: ReportService должен наследоваться от EmailSender, чтобы получить доступ к его полям легально",
      ],
      en: [
        "ReportService is tightly coupled to EmailSender's internals: it creates it itself, mutates its fields, and re-implements the sending protocol — those steps should be hidden inside EmailSender, with the client depending on a narrow interface like send(to, text)",
        "The problem is EmailSender's low cohesion: the connect and push methods should be split across two separate classes",
        "The main mistake is the string concatenation: switching from '+' to template literals will make the coupling go away",
        "The code violates the LSP: ReportService should inherit from EmailSender to gain legitimate access to its fields",
      ],
    },
    correctIndex: 0,
    explanation: {
      ru: "Верен первый вариант: это content coupling — ReportService знает поле host, флаг connected и правильную последовательность connect → push, то есть повторяет у себя протокол чужого модуля; любая правка EmailSender сломает всех таких клиентов. Лечение — information hiding: спрятать соединение и формирование письма внутри EmailSender, выставить узкий метод (или интерфейс Notifier) и получать зависимость извне, а не создавать через new. Второй вариант неверен: connect и push служат одной задаче отправки почты — их разделение как раз снизило бы cohesion. Третий неверен: способ склейки строк — косметика, зацепление создают знание чужих внутренностей, а не оператор '+'. Четвёртый неверен: наследование ради доступа к полям не «легализует», а максимально усиливает зацепление и не имеет отношения к LSP.",
      en: "The first option is correct: this is content coupling — ReportService knows the host field, the connected flag, and the correct connect → push sequence, i.e. it duplicates another module's protocol inside itself; any change to EmailSender will break every client like this. The cure is information hiding: tuck the connection and the message assembly inside EmailSender, expose a narrow method (or a Notifier interface), and receive the dependency from the outside rather than creating it with new. The second option is wrong: connect and push both serve the single task of sending mail — separating them would actually lower cohesion. The third is wrong: how the strings are joined is cosmetic — coupling comes from knowing another object's internals, not from the '+' operator. The fourth is wrong: inheriting just to reach the fields doesn't \"legitimize\" anything — it maximizes coupling and has nothing to do with the LSP.",
    },
    conceptId: "coupling-cohesion",
  },
  {
    id: "t-dry-vs-duplication-1",
    type: "tradeoff",
    category: "tradeoff",
    grade: "middle",
    prompt: {
      ru: "В чём суть компромисса DRY vs Duplication?",
      en: "What is the essence of the DRY vs Duplication trade-off?",
    },
    options: {
      ru: [
        "Любое повторение кода — ошибка, и его нужно устранять сразу при первом появлении",
        "Устранение дублирования знания защищает от рассинхронизации правил, но объединение случайно похожего кода создаёт ложную абстракцию и связывает независимые части",
        "DRY касается только текста кода: одинаковые строки обязаны стать одной функцией независимо от их смысла",
        "Дублирование всегда предпочтительнее общего кода, потому что абстракции усложняют систему",
      ],
      en: [
        "Any repetition of code is a mistake and must be eliminated the moment it first appears",
        "Eliminating duplicated knowledge protects against rules drifting out of sync, but merging incidentally similar code creates a false abstraction and couples independent parts",
        "DRY is only about the text of the code: identical lines must become a single function regardless of their meaning",
        "Duplication is always preferable to shared code, because abstractions complicate the system",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "DRY — про единственное представление знания: если копии выражают одно правило, их рассинхронизация даёт тихие баги, поэтому знание выносят в единый источник. Но у обобщения есть цена: склеенный по случайному сходству код связывает независимых клиентов и обрастает флагами — неверная абстракция дороже дублирования (Sandi Metz). Первый вариант неверен: раннее устранение любого повторения ведёт к преждевременным обобщениям, отсюда Rule of Three. Третий неверен: DRY у Hunt и Thomas сформулирован про знание, а не про текст кода — текстуальное совпадение не обязано быть дублированием. Четвёртый — противоположная крайность: отказ от DRY для настоящего дублирования знания гарантирует рассинхронизацию правил.",
      en: "DRY is about a single representation of knowledge: if the copies express one rule, letting them drift out of sync produces silent bugs, so the knowledge is extracted into a single source. But generalization has a price: code merged on the basis of incidental similarity couples independent callers and accumulates flags — the wrong abstraction costs more than duplication (Sandi Metz). The first option is wrong: eliminating every repetition early leads to premature generalization, which is exactly why the Rule of Three exists. The third is wrong: Hunt and Thomas framed DRY in terms of knowledge, not the text of the code — a textual match need not be duplication. The fourth is the opposite extreme: abandoning DRY for genuine duplication of knowledge guarantees that the rules drift out of sync.",
    },
    conceptId: "dry-vs-duplication",
  },
  {
    id: "cs-dry-vs-duplication-1",
    type: "code-smell",
    category: "tradeoff",
    grade: "middle",
    prompt: {
      ru: "Что не так в этом коде и как его улучшить?",
      en: "What is wrong with this code and how would you improve it?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "interface CartItem { price: number; qty: number; }",
          "interface InvoiceLine { amount: number; }",
          "",
          "function checkoutTotal(items: CartItem[]) {",
          "  const subtotal = items.reduce((s, i) => s + i.price * i.qty, 0);",
          "  return subtotal * 1.2; // +20% НДС",
          "}",
          "",
          "function invoiceTotal(lines: InvoiceLine[]) {",
          "  const subtotal = lines.reduce((s, l) => s + l.amount, 0);",
          "  return subtotal * 1.2; // +20% НДС",
          "}",
        ].join('\n'),
        en: [
          "interface CartItem { price: number; qty: number; }",
          "interface InvoiceLine { amount: number; }",
          "",
          "function checkoutTotal(items: CartItem[]) {",
          "  const subtotal = items.reduce((s, i) => s + i.price * i.qty, 0);",
          "  return subtotal * 1.2; // +20% VAT",
          "}",
          "",
          "function invoiceTotal(lines: InvoiceLine[]) {",
          "  const subtotal = lines.reduce((s, l) => s + l.amount, 0);",
          "  return subtotal * 1.2; // +20% VAT",
          "}",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "Ставка НДС — одно бизнес-знание, продублированное «магическим числом» в двух функциях; её нужно вынести в единый источник (константу или функцию applyVat)",
        "Функции почти одинаковы — нужно слить их в одну универсальную calcTotal с флагом, различающим корзину и счёт",
        "Всё в порядке: две строки повторения допустимы по правилу трёх, менять ничего не нужно",
        "Проблема в производительности: reduce вычисляется в обеих функциях и его нужно кешировать",
      ],
      en: [
        "The VAT rate is a single piece of business knowledge duplicated as a \"magic number\" in two functions; it should be extracted into a single source (a constant or an applyVat function)",
        "The functions are almost identical — they should be merged into one all-purpose calcTotal with a flag that distinguishes the cart from the invoice",
        "Everything is fine: two lines of repetition are acceptable under the Rule of Three, so nothing needs to change",
        "The problem is performance: reduce runs in both functions and should be cached",
      ],
    },
    correctIndex: 0,
    explanation: {
      ru: "Множитель 1.2 в обеих функциях — это одно и то же знание (ставка НДС). При изменении ставки одну копию поправят, вторую забудут — тихая рассинхронизация. Правильное лечение — единый источник: const VAT_RATE = 0.2 или функция applyVat(subtotal). Второй вариант — типичная ложная абстракция: суммирование корзины и счёта совпало лишь текстуально, у них разные типы и разные причины изменения, а флаг-переключатель связал бы их. Третий вариант неверен: Rule of Three относится к случайному сходству кода, а не к дублированному бизнес-правилу — знание выносится сразу. Четвёртый вариант не по делу: reduce по разным массивам не является проблемой производительности, и кеширование здесь ничего не улучшает.",
      en: "The 1.2 multiplier in both functions is the same piece of knowledge (the VAT rate). When the rate changes, one copy gets fixed and the other is forgotten — a silent drift out of sync. The right fix is a single source: const VAT_RATE = 0.2 or an applyVat(subtotal) function. The second option is a classic false abstraction: summing the cart and summing the invoice match only textually — they have different types and different reasons to change, and a toggle flag would couple them. The third option is wrong: the Rule of Three applies to incidental code similarity, not to a duplicated business rule — knowledge is extracted right away. The fourth option is beside the point: running reduce over different arrays is not a performance problem, and caching would improve nothing here.",
    },
    conceptId: "dry-vs-duplication",
  },
  {
    id: "t-abstraction-cost-1",
    type: "tradeoff",
    category: "tradeoff",
    grade: "senior",
    prompt: {
      ru: "В чём суть компромисса «цены абстракции» (Abstraction Cost)?",
      en: "What is the essence of the Abstraction Cost trade-off?",
    },
    options: {
      ru: [
        "Абстракции всегда замедляют выполнение программы, поэтому в критичном к производительности коде их нужно избегать полностью",
        "Абстракция снижает связанность и скрывает детали, но добавляет косвенность и когнитивную нагрузку — она оправдана, только когда выгода от развязки превышает эту цену",
        "Чем больше уровней абстракции в системе, тем лучше архитектура: каждый новый слой дополнительно уменьшает зацепление модулей",
        "Цена абстракции — временная: как только команда привыкает к слоям, косвенность перестаёт что-либо стоить",
      ],
      en: [
        "Abstractions always slow down program execution, so in performance-critical code they should be avoided entirely",
        "An abstraction reduces coupling and hides details but adds indirection and cognitive load — it is justified only when the benefit of decoupling outweighs that cost",
        "The more levels of abstraction a system has, the better the architecture: each new layer further reduces coupling between modules",
        "The cost of abstraction is temporary: once the team gets used to the layers, indirection stops costing anything",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "Верен второй вариант: абстракция — это инвестиция, у которой есть и выгода (развязка, сокрытие деталей, точка подмены), и цена (косвенность, нагрузка при чтении и отладке, риск протечки деталей — Law of Leaky Abstractions). Решение о её введении — это взвешивание одного против другого. Первый вариант неверен: главная цена абстракции — когнитивная, а не вычислительная; накладные расходы в рантайме часто пренебрежимы, и «избегать полностью» — ложный вывод. Третий вариант неверен: слои сами по себе не улучшают архитектуру — каждый должен окупать свою косвенность, иначе это speculative generality. Четвёртый неверен: привычка не отменяет цену — путь чтения и отладки через лишние слои остаётся длиннее для каждого нового участника и при каждом расследовании бага.",
      en: "The second option is correct: an abstraction is an investment with both a benefit (decoupling, hiding details, a substitution point) and a cost (indirection, the load of reading and debugging, the risk of leaking details — the Law of Leaky Abstractions). Deciding to introduce it means weighing one against the other. The first option is wrong: the main cost of an abstraction is cognitive, not computational; runtime overhead is often negligible, and \"avoid entirely\" is a false conclusion. The third option is wrong: layers do not improve an architecture by themselves — each must earn its indirection, otherwise it is speculative generality. The fourth is wrong: familiarity does not cancel the cost — the path of reading and debugging through extra layers stays longer for every new team member and during every bug investigation.",
    },
    conceptId: "abstraction-cost",
  },
  {
    id: "cs-abstraction-cost-1",
    type: "code-smell",
    category: "tradeoff",
    grade: "senior",
    prompt: {
      ru: "Во всём приложении ровно одна реализация приветствия и один вызов. Что не так с этим кодом и как его улучшить?",
      en: "The entire application has exactly one greeting implementation and one call site. What is wrong with this code and how would you improve it?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "interface GreetingProvider { greet(name: string): string; }",
          "",
          "class DefaultGreetingProvider implements GreetingProvider {",
          "  greet(name: string) { return `Hello, ${name}!`; }",
          "}",
          "",
          "class GreetingProviderFactory {",
          "  static create(): GreetingProvider { return new DefaultGreetingProvider(); }",
          "}",
          "",
          "class GreetingService {",
          "  private provider = GreetingProviderFactory.create();",
          "  greet(name: string) { return this.provider.greet(name); }",
          "}",
          "",
          "// единственный вызов во всём приложении:",
          "console.log(new GreetingService().greet('Ann'));",
        ].join('\n'),
        en: [
          "interface GreetingProvider { greet(name: string): string; }",
          "",
          "class DefaultGreetingProvider implements GreetingProvider {",
          "  greet(name: string) { return `Hello, ${name}!`; }",
          "}",
          "",
          "class GreetingProviderFactory {",
          "  static create(): GreetingProvider { return new DefaultGreetingProvider(); }",
          "}",
          "",
          "class GreetingService {",
          "  private provider = GreetingProviderFactory.create();",
          "  greet(name: string) { return this.provider.greet(name); }",
          "}",
          "",
          "// the only call site in the entire application:",
          "console.log(new GreetingService().greet('Ann'));",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "Нарушен SRP: GreetingService совмещает создание провайдера и приветствие — нужно вынести создание в отдельный класс-инжектор",
        "Вокруг одной тривиальной реализации построены три слоя косвенности без выгоды — стоит заменить всё простой функцией и вводить интерфейс, когда появится вторая реализация",
        "Не хватает ещё одного уровня: нужен интерфейс IGreetingService и регистрация в DI-контейнере, чтобы архитектура стала расширяемой",
        "Проблема в статическом методе фабрики: если сделать create() методом экземпляра, дизайн станет корректным",
      ],
      en: [
        "The SRP is violated: GreetingService combines creating the provider with greeting — the creation should be extracted into a separate injector class",
        "Three layers of indirection have been built around a single trivial implementation with no benefit — the whole thing should be replaced with a plain function, and an interface introduced once a second implementation appears",
        "One more level is missing: an IGreetingService interface and registration in a DI container are needed to make the architecture extensible",
        "The problem is the static factory method: making create() an instance method would make the design correct",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "Верен второй вариант: интерфейс, фабрика и сервис-обёртка обслуживают единственную тривиальную реализацию с единственным вызовом — выгоды (подмена, развязка) нет, а цена косвенности есть. Это speculative generality: правильный ход — одна функция greet(name), а абстракцию вводить, когда появится реальная вторая реализация или потребность в подмене (например, в тестах). Первый вариант неверен: формально можно придраться к SRP, но вынесение создания в ещё один класс лишь добавит четвёртый слой — он лечит симптом, усугубляя болезнь. Третий вариант неверен по той же причине: DI-контейнер и ещё один интерфейс увеличивают цену абстракции без какой-либо новой выгоды. Четвёртый неверен: статичность фабричного метода — косметическая деталь; проблема не в форме фабрики, а в том, что фабрика здесь вообще не нужна.",
      en: "The second option is correct: the interface, the factory, and the service wrapper serve a single trivial implementation with a single call site — there is no benefit (substitution, decoupling), only the cost of indirection. This is speculative generality: the right move is a single greet(name) function, introducing an abstraction when a real second implementation or a need for substitution (in tests, for example) actually appears. The first option is wrong: you could formally nitpick about the SRP, but extracting the creation into yet another class only adds a fourth layer — it treats the symptom while making the disease worse. The third option is wrong for the same reason: a DI container and another interface increase the cost of abstraction without any new benefit. The fourth is wrong: whether the factory method is static is a cosmetic detail; the problem is not the form of the factory but that a factory is not needed here at all.",
    },
    conceptId: "abstraction-cost",
  },
  {
    id: "t-yagni-vs-flexibility-1",
    type: "tradeoff",
    category: "tradeoff",
    grade: "senior",
    prompt: {
      ru: "В чём суть компромисса между YAGNI и проектированием гибкости «на вырост»?",
      en: "What is the essence of the trade-off between YAGNI and designing flexibility \"to grow into\"?",
    },
    options: {
      ru: [
        "YAGNI запрещает вводить абстракции и интерфейсы, поэтому выбор — между чистым кодом и работающим",
        "Отказ от спекулятивных точек расширения удешевляет код сейчас, но если требование всё же появится, придётся платить рефакторингом",
        "Гибкость «на будущее» всегда окупается: требования неизбежно растут, поэтому закладывать её нужно везде",
        "YAGNI применим только к прототипам; в продакшен-коде все точки расширения нужно закладывать заранее",
      ],
      en: [
        "YAGNI forbids introducing abstractions and interfaces, so the choice is between clean code and working code",
        "Forgoing speculative extension points makes the code cheaper now, but if the requirement does appear, you'll have to pay with refactoring",
        "Future-proofing flexibility always pays off: requirements inevitably grow, so you should build it in everywhere",
        "YAGNI applies only to prototypes; in production code all extension points should be built in up front",
      ],
    },
    correctIndex: 1,
    explanation: {
      ru: "Верен второй вариант: YAGNI — это ставка на то, что стоимость простого решения сейчас плюс возможный рефакторинг потом ниже, чем стоимость написания, сопровождения и чтения гибкости, которая может не понадобиться или оказаться не на той оси изменчивости. Первый вариант искажает принцип: YAGNI не запрещает абстракции — он откладывает их до реальной потребности. Третий вариант — как раз то заблуждение, против которого направлен YAGNI: предсказанные требования часто не наступают, а «всегда окупается» недоказуемо. Четвёртый неверен: YAGNI сформулирован именно для продакшен-разработки (XP) и опирается на тесты и рефакторинг, а не на статус кода как прототипа.",
      en: "The second option is correct: YAGNI is a bet that the cost of a simple solution now plus possible refactoring later is lower than the cost of writing, maintaining, and reading flexibility that may never be needed or may turn out to be on the wrong axis of change. The first option distorts the principle: YAGNI doesn't forbid abstractions — it defers them until there's a real need. The third option is exactly the fallacy YAGNI targets: predicted requirements often never materialize, and \"always pays off\" is unprovable. The fourth is wrong: YAGNI was formulated specifically for production development (XP) and relies on tests and refactoring, not on the code's status as a prototype.",
    },
    conceptId: "yagni-vs-flexibility",
  },
  {
    id: "cs-yagni-vs-flexibility-1",
    type: "code-smell",
    category: "tradeoff",
    grade: "senior",
    prompt: {
      ru: "В продукте есть ровно один способ уведомления — email, других требований в планах нет. Что не так с этим дизайном и как его улучшить?",
      en: "The product has exactly one notification method — email — and no other requirements are planned. What's wrong with this design and how would you improve it?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "interface NotificationChannel<TPayload, TResult> {",
          "  send(payload: TPayload): Promise<TResult>;",
          "}",
          "",
          "class ChannelRegistry {",
          "  private channels = new Map<string, NotificationChannel<any, any>>();",
          "  register(name: string, ch: NotificationChannel<any, any>) { this.channels.set(name, ch); }",
          "  resolve(name: string) { return this.channels.get(name); }",
          "}",
          "",
          "class EmailChannel implements NotificationChannel<string, void> {",
          "  async send(text: string) { console.log(`email: ${text}`); }",
          "}",
          "",
          "const registry = new ChannelRegistry();",
          "registry.register('email', new EmailChannel());",
        ].join('\n'),
        en: [
          "interface NotificationChannel<TPayload, TResult> {",
          "  send(payload: TPayload): Promise<TResult>;",
          "}",
          "",
          "class ChannelRegistry {",
          "  private channels = new Map<string, NotificationChannel<any, any>>();",
          "  register(name: string, ch: NotificationChannel<any, any>) { this.channels.set(name, ch); }",
          "  resolve(name: string) { return this.channels.get(name); }",
          "}",
          "",
          "class EmailChannel implements NotificationChannel<string, void> {",
          "  async send(text: string) { console.log(`email: ${text}`); }",
          "}",
          "",
          "const registry = new ChannelRegistry();",
          "registry.register('email', new EmailChannel());",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "Нарушен LSP: EmailChannel не взаимозаменяем с базовым типом NotificationChannel и его нельзя класть в реестр",
        "Нарушен DRY: логика отправки дублируется между ChannelRegistry и EmailChannel — её нужно вынести в общий базовый класс",
        "Speculative generality: реестр, строковые ключи и обобщённые типы построены под несуществующие каналы — для единственного сценария достаточно простого EmailChannel или функции sendEmail, а реестр ввести при втором реальном канале",
        "Не хватает гибкости: стоит добавить абстрактную фабрику каналов, чтобы SMS и push потом подключались без правок кода",
      ],
      en: [
        "LSP is violated: EmailChannel isn't substitutable for the base type NotificationChannel and can't be placed in the registry",
        "DRY is violated: the sending logic is duplicated between ChannelRegistry and EmailChannel and should be extracted into a shared base class",
        "Speculative generality: the registry, string keys, and generic types are built for channels that don't exist — for the single scenario a plain EmailChannel or a sendEmail function is enough, and the registry can be introduced when a second real channel appears",
        "It lacks flexibility: you should add an abstract channel factory so that SMS and push can later be plugged in without code changes",
      ],
    },
    correctIndex: 2,
    explanation: {
      ru: "Верен третий вариант: это классическая спекулятивная общность (Fowler: speculative generality) — реестр с поиском по строковому имени, дженерики TPayload/TResult и слой регистрации обслуживают каналы, которых не существует и которые не запланированы. Вся эта механика (плюс any, разрушающий типобезопасность) — цена гибкости, за которой не стоит ни одного требования; по YAGNI достаточно прямого EmailChannel или функции sendEmail, а точку расширения ввести при появлении второго канала, когда станет ясна реальная ось изменчивости. Первый вариант неверен: EmailChannel корректно реализует интерфейс, контракт не нарушен — проблема не в подстановке типов. Второй неверен: реестр ничего не отправляет, дублирования логики нет, и общий базовый класс лишь добавил бы ещё один спекулятивный слой. Четвёртый предлагает усугубить проблему: добавить ещё больше гибкости под гипотетические SMS и push — ровно то преждевременное обобщение, от которого YAGNI предостерегает.",
      en: "The third option is correct: this is classic speculative generality (Fowler's term) — a registry with lookup by string name, the TPayload/TResult generics, and a registration layer all serve channels that don't exist and aren't planned. All this machinery (plus the any that destroys type safety) is the price of flexibility that not a single requirement backs; by YAGNI, a direct EmailChannel or a sendEmail function is enough, and the extension point can be introduced when a second channel appears and the real axis of change becomes clear. The first option is wrong: EmailChannel implements the interface correctly and the contract isn't broken — the problem isn't type substitution. The second is wrong: the registry doesn't send anything, there's no duplicated logic, and a shared base class would only add yet another speculative layer. The fourth proposes making things worse: adding even more flexibility for hypothetical SMS and push — exactly the premature generalization YAGNI warns against.",
    },
    conceptId: "yagni-vs-flexibility",
  },
  {
    id: "t-performance-vs-readability-1",
    type: "tradeoff",
    category: "tradeoff",
    grade: "lead",
    prompt: {
      ru: "Как грамотно разрешать компромисс между производительностью и читаемостью кода?",
      en: "How should you soundly resolve the trade-off between performance and code readability?",
    },
    options: {
      ru: [
        "По умолчанию писать читаемый код, а жертвовать читаемостью только на горячих путях, подтверждённых профилировщиком, изолируя и документируя оптимизацию",
        "Производительный код по природе нечитаем, поэтому команда должна один раз выбрать приоритет на уровне всего проекта и применять его везде",
        "Читаемость субъективна и не измерима, поэтому при любом конфликте приоритет всегда за производительностью",
        "Микрооптимизации стоит закладывать во весь код заранее, чтобы потом не пришлось переписывать горячие пути",
      ],
      en: [
        "Write readable code by default, and sacrifice readability only on hot paths confirmed by the profiler, isolating and documenting the optimization",
        "Performant code is inherently unreadable, so the team should choose a priority once at the whole-project level and apply it everywhere",
        "Readability is subjective and unmeasurable, so in any conflict performance always takes priority",
        "Micro-optimizations should be baked into all the code up front, so you don't have to rewrite hot paths later",
      ],
    },
    correctIndex: 0,
    explanation: {
      ru: "Верен первый вариант: это классическая позиция Knuth («premature optimization is the root of all evil») — по умолчанию код пишут для людей, а нечитаемые оптимизации допускают точечно, по данным измерений, изолируя их за понятным интерфейсом с задокументированным бенчмарком. Второй вариант неверен: это не бинарный выбор на уровне проекта — горячих путей обычно единицы процентов кода, и решение принимается локально. Третий неверен: читаемость напрямую влияет на стоимость изменений и число дефектов, а безусловный приоритет производительности ведёт к неоправданной сложности в холодном коде. Четвёртый описывает преждевременную оптимизацию в чистом виде: интуиция о будущих узких местах систематически ошибается, а вся кодовая база становится дороже в сопровождении.",
      en: "The first option is correct: this is Knuth's classic stance (\"premature optimization is the root of all evil\") — by default code is written for people, and unreadable optimizations are permitted selectively, driven by measurements, isolated behind a clear interface with a documented benchmark. The second option is wrong: this isn't a binary, project-wide choice — hot paths are usually a few percent of the code, and the decision is made locally. The third is wrong: readability directly affects the cost of change and the number of defects, and an unconditional priority on performance leads to unwarranted complexity in cold code. The fourth describes premature optimization in its purest form: intuition about future bottlenecks is systematically wrong, and the entire codebase becomes more expensive to maintain.",
    },
    conceptId: "performance-vs-readability",
  },
  {
    id: "cs-performance-vs-readability-1",
    type: "code-smell",
    category: "tradeoff",
    grade: "lead",
    prompt: {
      ru: "Функция формирует список для админ-отчёта, который запрашивают несколько раз в день на сотнях записей. Что не так с этим кодом и как его улучшить?",
      en: "A function builds a list for an admin report that's requested a few times a day over hundreds of records. What's wrong with this code and how would you improve it?",
    },
    code: {
      lang: "typescript",
      code: {
        ru: [
          "interface User { active: boolean; name: string; }",
          "",
          "// Админ-отчёт: вызывается несколько раз в день, users — сотни записей",
          "function activeUserNames(users: User[]): string[] {",
          "  const res: string[] = new Array(users.length); // предвыделяем буфер",
          "  let j = 0;",
          "  for (let i = 0, len = users.length; i < len; ++i) {",
          "    const u = users[i];",
          "    if (u.active) res[j++] = u.name;",
          "  }",
          "  res.length = j; // обрезаем неиспользованный хвост",
          "  return res;",
          "}",
        ].join('\n'),
        en: [
          "interface User { active: boolean; name: string; }",
          "",
          "// Admin report: called a few times a day, users is hundreds of records",
          "function activeUserNames(users: User[]): string[] {",
          "  const res: string[] = new Array(users.length); // preallocate the buffer",
          "  let j = 0;",
          "  for (let i = 0, len = users.length; i < len; ++i) {",
          "    const u = users[i];",
          "    if (u.active) res[j++] = u.name;",
          "  }",
          "  res.length = j; // trim the unused tail",
          "  return res;",
          "}",
        ].join('\n'),
      },
    },
    options: {
      ru: [
        "Преждевременная микрооптимизация холодного пути: без данных профилировщика читаемый filter/map здесь лучше, а оптимизировать стоит только измеренные горячие места",
        "Код недостаточно быстрый: нужно пойти дальше и заменить массив строк на предвыделенный типизированный буфер с индексами",
        "Проблема только в мутации res.length — заменить её на slice(0, j), остальное оставить как есть",
        "Всё в порядке: ручные циклы всегда предпочтительнее filter/map в production-коде",
      ],
      en: [
        "Premature micro-optimization of a cold path: without profiler data a readable filter/map is better here, and only measured hot spots are worth optimizing",
        "The code isn't fast enough: you should go further and replace the array of strings with a preallocated typed buffer addressed by index",
        "The only problem is mutating res.length — replace it with slice(0, j) and leave the rest as is",
        "It's fine: hand-rolled loops are always preferable to filter/map in production code",
      ],
    },
    correctIndex: 0,
    explanation: {
      ru: "Верен первый вариант: функция вызывается несколько раз в день на сотнях элементов — это заведомо холодный путь, и выигрыш от предвыделенного буфера, ручного счётчика j и кэширования len здесь неотличим от нуля, а читаемость страдает заметно. Идиоматичное users.filter((u) => u.active).map((u) => u.name) выражает намерение одной строкой; жертвовать этим стоит только после профилирования. Второй вариант усугубляет проблему — ещё больше сложности на пути, где производительность не важна. Третий чинит косметическую деталь, не устраняя корневой smell: неоправданную оптимизацию как таковую. Четвёртый — ложное обобщение: ручные циклы оправданы на измеренных горячих путях, но правилом по умолчанию быть не должны.",
      en: "The first option is correct: the function is called a few times a day over hundreds of elements — this is plainly a cold path, and the gain from a preallocated buffer, a manual counter j, and caching len is indistinguishable from zero here, while readability suffers noticeably. The idiomatic users.filter((u) => u.active).map((u) => u.name) expresses the intent in a single line; sacrificing that is only worth it after profiling. The second option makes the problem worse — yet more complexity on a path where performance doesn't matter. The third fixes a cosmetic detail without removing the root smell: the unwarranted optimization itself. The fourth is a false generalization: hand-rolled loops are justified on measured hot paths, but shouldn't be the default rule.",
    },
    conceptId: "performance-vs-readability",
  },
];
